// /// Generated by mate_flutter, please don't edit! Created time: 2023-03-11 13:17:25.182135

import 'dart:core';
import 'package:flutter/src/animation/tween.dart';
import 'dart:ui';
import 'package:flutter/src/animation/curves.dart';
export 'dart:ui' show Color, Rect, Size;
export 'animation.dart' show Animation;
export 'curves.dart' show Curve;

/// class Tween<T extends Object?> extends Animatable<T>
class Tween$Mate<T extends Object?> extends Tween<T> {
  /// Tween<T> Tween({T? begin, T? end})
  Tween$Mate({
    /// param: {T? begin}
    T? begin,

    /// param: {T? end}
    T? end,
  }) : super(
          begin: begin,
          end: end,
        ) {}
}

/// class ReverseTween<T extends Object?> extends Tween<T>
class ReverseTween$Mate<T extends Object?> extends ReverseTween<T> {
  /// ReverseTween<T> ReverseTween(Tween<T> parent)
  ReverseTween$Mate(

      /// param: Tween<T> parent
      Tween<T> parent)
      : super(parent) {}
}

/// class ColorTween extends Tween<Color?>
class ColorTween$Mate extends ColorTween {
  /// ColorTween ColorTween({Color? begin, Color? end})
  ColorTween$Mate({
    /// param: {Color? begin}
    Color? begin,

    /// param: {Color? end}
    Color? end,
  }) : super(
          begin: begin,
          end: end,
        ) {}
}

/// class SizeTween extends Tween<Size?>
class SizeTween$Mate extends SizeTween {
  /// SizeTween SizeTween({Size? begin, Size? end})
  SizeTween$Mate({
    /// param: {Size? begin}
    Size? begin,

    /// param: {Size? end}
    Size? end,
  }) : super(
          begin: begin,
          end: end,
        ) {}
}

/// class RectTween extends Tween<Rect?>
class RectTween$Mate extends RectTween {
  /// RectTween RectTween({Rect? begin, Rect? end})
  RectTween$Mate({
    /// param: {Rect? begin}
    Rect? begin,

    /// param: {Rect? end}
    Rect? end,
  }) : super(
          begin: begin,
          end: end,
        ) {}
}

/// class IntTween extends Tween<int>
class IntTween$Mate extends IntTween {
  /// IntTween IntTween({int? begin, int? end})
  IntTween$Mate({
    /// param: {int? begin}
    int? begin,

    /// param: {int? end}
    int? end,
  }) : super(
          begin: begin,
          end: end,
        ) {}
}

/// class StepTween extends Tween<int>
class StepTween$Mate extends StepTween {
  /// StepTween StepTween({int? begin, int? end})
  StepTween$Mate({
    /// param: {int? begin}
    int? begin,

    /// param: {int? end}
    int? end,
  }) : super(
          begin: begin,
          end: end,
        ) {}
}

/// class ConstantTween<T> extends Tween<T>
class ConstantTween$Mate<T> extends ConstantTween<T> {
  /// ConstantTween<T> ConstantTween(T value)
  ConstantTween$Mate(

      /// param: T value
      T value)
      : super(value) {}
}

/// class CurveTween extends Animatable<double>
class CurveTween$Mate extends CurveTween {
  /// CurveTween CurveTween({required Curve curve})
  CurveTween$Mate(
      {
      /// param: {required Curve curve}
      required Curve curve})
      : super(curve: curve) {}
}
