// /// Generated by mat_flutter, please don't edit! Created time: 2023-03-09 00:16:01.951675

library;

import 'package:flutter/src/foundation/key.dart';
import 'dart:core';

/// class Spacer extends StatelessWidget
class SpacerMate {
  /// Spacer Spacer({Key? key, int flex = 1})
  SpacerMate({
// param: {Key? key}
    Key? key,
// param: {int flex = 1}
    required int flex,
  }) {}
}
