// /// Generated by mat_flutter, please don't edit! Created time: 2023-03-09 00:16:01.957171

library;

import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/animation/animation.dart';
import 'dart:core';

/// abstract class StatusTransitionWidget extends StatefulWidget
abstract class StatusTransitionWidgetMate {
  /// StatusTransitionWidget StatusTransitionWidget({Key? key, required Animation<double> animation})
  StatusTransitionWidgetMate({
// param: {Key? key}
    Key? key,
// param: {required Animation<double> animation}
    required Animation<double> animation,
  }) {}
}
