// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/material/about.dart';
import 'package:note/mate.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'dart:core';

/// class AboutListTile extends StatelessWidget
class AboutListTile$Mate extends AboutListTile with Mate {
  /// AboutListTile AboutListTile({Key? key, Widget? icon, Widget? child, String? applicationName, String? applicationVersion, Widget? applicationIcon, String? applicationLegalese, List<Widget>? aboutBoxChildren, bool? dense})
  AboutListTile$Mate({
    /// optionalParameters: {Key? key} , defaultValue:none
    Key? key,

    /// optionalParameters: {Widget? icon} , defaultValue:none
    Widget? icon,

    /// optionalParameters: {Widget? child} , defaultValue:none
    Widget? child,

    /// optionalParameters: {String? applicationName} , defaultValue:none
    String? applicationName,

    /// optionalParameters: {String? applicationVersion} , defaultValue:none
    String? applicationVersion,

    /// optionalParameters: {Widget? applicationIcon} , defaultValue:none
    Widget? applicationIcon,

    /// optionalParameters: {String? applicationLegalese} , defaultValue:none
    String? applicationLegalese,

    /// optionalParameters: {List<Widget>? aboutBoxChildren} , defaultValue:none
    List<Widget>? aboutBoxChildren,

    /// optionalParameters: {bool? dense} , defaultValue:none
    bool? dense,
  }) : super(
          key: key,
          icon: icon,
          child: child,
          applicationName: applicationName,
          applicationVersion: applicationVersion,
          applicationIcon: applicationIcon,
          applicationLegalese: applicationLegalese,
          aboutBoxChildren: aboutBoxChildren,
          dense: dense,
        ) {
    mateBuilder = (p) => AboutListTile$Mate(
          key: p.get('key').build(),
          icon: p.get('icon').build(),
          child: p.get('child').build(),
          applicationName: p.get('applicationName').build(),
          applicationVersion: p.get('applicationVersion').build(),
          applicationIcon: p.get('applicationIcon').build(),
          applicationLegalese: p.get('applicationLegalese').build(),
          aboutBoxChildren: p.get('aboutBoxChildren').build(),
          dense: p.get('dense').build(),
        );
    mateDeclare('key', key);
    mateDeclare('icon', icon);
    mateDeclare('child', child);
    mateDeclare('applicationName', applicationName);
    mateDeclare('applicationVersion', applicationVersion);
    mateDeclare('applicationIcon', applicationIcon);
    mateDeclare('applicationLegalese', applicationLegalese);
    mateDeclare('aboutBoxChildren', aboutBoxChildren);
    mateDeclare('dense', dense);
  }
}

/// class AboutDialog extends StatelessWidget
class AboutDialog$Mate extends AboutDialog with Mate {
  /// AboutDialog AboutDialog({Key? key, String? applicationName, String? applicationVersion, Widget? applicationIcon, String? applicationLegalese, List<Widget>? children})
  AboutDialog$Mate({
    /// optionalParameters: {Key? key} , defaultValue:none
    Key? key,

    /// optionalParameters: {String? applicationName} , defaultValue:none
    String? applicationName,

    /// optionalParameters: {String? applicationVersion} , defaultValue:none
    String? applicationVersion,

    /// optionalParameters: {Widget? applicationIcon} , defaultValue:none
    Widget? applicationIcon,

    /// optionalParameters: {String? applicationLegalese} , defaultValue:none
    String? applicationLegalese,

    /// optionalParameters: {List<Widget>? children} , defaultValue:none
    List<Widget>? children,
  }) : super(
          key: key,
          applicationName: applicationName,
          applicationVersion: applicationVersion,
          applicationIcon: applicationIcon,
          applicationLegalese: applicationLegalese,
          children: children,
        ) {
    mateBuilder = (p) => AboutDialog$Mate(
          key: p.get('key').build(),
          applicationName: p.get('applicationName').build(),
          applicationVersion: p.get('applicationVersion').build(),
          applicationIcon: p.get('applicationIcon').build(),
          applicationLegalese: p.get('applicationLegalese').build(),
          children: p.get('children').build(),
        );
    mateDeclare('key', key);
    mateDeclare('applicationName', applicationName);
    mateDeclare('applicationVersion', applicationVersion);
    mateDeclare('applicationIcon', applicationIcon);
    mateDeclare('applicationLegalese', applicationLegalese);
    mateDeclare('children', children);
  }
}

/// class LicensePage extends StatefulWidget
class LicensePage$Mate extends LicensePage with Mate {
  /// LicensePage LicensePage({Key? key, String? applicationName, String? applicationVersion, Widget? applicationIcon, String? applicationLegalese})
  LicensePage$Mate({
    /// optionalParameters: {Key? key} , defaultValue:none
    Key? key,

    /// optionalParameters: {String? applicationName} , defaultValue:none
    String? applicationName,

    /// optionalParameters: {String? applicationVersion} , defaultValue:none
    String? applicationVersion,

    /// optionalParameters: {Widget? applicationIcon} , defaultValue:none
    Widget? applicationIcon,

    /// optionalParameters: {String? applicationLegalese} , defaultValue:none
    String? applicationLegalese,
  }) : super(
          key: key,
          applicationName: applicationName,
          applicationVersion: applicationVersion,
          applicationIcon: applicationIcon,
          applicationLegalese: applicationLegalese,
        ) {
    mateBuilder = (p) => LicensePage$Mate(
          key: p.get('key').build(),
          applicationName: p.get('applicationName').build(),
          applicationVersion: p.get('applicationVersion').build(),
          applicationIcon: p.get('applicationIcon').build(),
          applicationLegalese: p.get('applicationLegalese').build(),
        );
    mateDeclare('key', key);
    mateDeclare('applicationName', applicationName);
    mateDeclare('applicationVersion', applicationVersion);
    mateDeclare('applicationIcon', applicationIcon);
    mateDeclare('applicationLegalese', applicationLegalese);
  }
}
