// /// Generated by gen_maters.dart, please don't edit!

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/src/material/switch_list_tile.dart' as _i1;
import 'package:note/mate.dart' as _i2;
import 'package:flutter/src/foundation/key.dart' as _i3;
import 'package:flutter/src/foundation/basic_types.dart' as _i4;
import 'dart:ui' as _i5;
import 'package:flutter/src/painting/image_provider.dart' as _i6;
import 'package:flutter/src/painting/image_stream.dart' as _i7;
import 'package:flutter/src/material/material_state.dart' as _i8;
import 'package:flutter/src/widgets/icon.dart' as _i9;
import 'package:flutter/src/material/theme_data.dart' as _i10;
import 'package:flutter/src/gestures/recognizer.dart' as _i11;
import 'package:flutter/gestures.dart' as _i12;
import 'package:flutter/src/services/mouse_cursor.dart' as _i13;
import 'package:flutter/src/widgets/focus_manager.dart' as _i14;
import 'package:flutter/src/widgets/framework.dart' as _i15;
import 'package:flutter/src/painting/edge_insets.dart' as _i16;
import 'package:flutter/src/material/list_tile.dart' as _i17;
import 'package:flutter/material.dart' as _i18;
import 'package:flutter/src/painting/borders.dart' as _i19;

/// class SwitchListTile extends StatelessWidget
class SwitchListTile$Mate extends _i1.SwitchListTile with _i2.Mate {
  /// SwitchListTile SwitchListTile({Key? key, required bool value, required void Function(bool)? onChanged, Color? activeColor, Color? activeTrackColor, Color? inactiveThumbColor, Color? inactiveTrackColor, ImageProvider<Object>? activeThumbImage, void Function(Object, StackTrace?)? onActiveThumbImageError, ImageProvider<Object>? inactiveThumbImage, void Function(Object, StackTrace?)? onInactiveThumbImageError, MaterialStateProperty<Color?>? thumbColor, MaterialStateProperty<Color?>? trackColor, MaterialStateProperty<Color?>? trackOutlineColor, MaterialStateProperty<Icon?>? thumbIcon, MaterialTapTargetSize? materialTapTargetSize, DragStartBehavior dragStartBehavior = DragStartBehavior.start, MouseCursor? mouseCursor, MaterialStateProperty<Color?>? overlayColor, double? splashRadius, FocusNode? focusNode, void Function(bool)? onFocusChange, bool autofocus = false, Color? tileColor, Widget? title, Widget? subtitle, bool isThreeLine = false, bool? dense, EdgeInsetsGeometry? contentPadding, Widget? secondary, bool selected = false, ListTileControlAffinity controlAffinity = ListTileControlAffinity.platform, ShapeBorder? shape, Color? selectedTileColor, VisualDensity? visualDensity, bool? enableFeedback, Color? hoverColor})
  SwitchListTile$Mate({
    /// optionalParameters: {Key? key} , default:none
    _i3.Key? key,

    /// optionalParameters: {required bool value} , default:none
    required bool value,

    /// optionalParameters: {required void Function(bool)? onChanged} , default:none
    required _i4.ValueChanged<bool>? onChanged,

    /// optionalParameters: {Color? activeColor} , default:none
    _i5.Color? activeColor,

    /// optionalParameters: {Color? activeTrackColor} , default:none
    _i5.Color? activeTrackColor,

    /// optionalParameters: {Color? inactiveThumbColor} , default:none
    _i5.Color? inactiveThumbColor,

    /// optionalParameters: {Color? inactiveTrackColor} , default:none
    _i5.Color? inactiveTrackColor,

    /// optionalParameters: {ImageProvider<Object>? activeThumbImage} , default:none
    _i6.ImageProvider<Object>? activeThumbImage,

    /// optionalParameters: {void Function(Object, StackTrace?)? onActiveThumbImageError} , default:none
    _i7.ImageErrorListener? onActiveThumbImageError,

    /// optionalParameters: {ImageProvider<Object>? inactiveThumbImage} , default:none
    _i6.ImageProvider<Object>? inactiveThumbImage,

    /// optionalParameters: {void Function(Object, StackTrace?)? onInactiveThumbImageError} , default:none
    _i7.ImageErrorListener? onInactiveThumbImageError,

    /// optionalParameters: {MaterialStateProperty<Color?>? thumbColor} , default:none
    _i8.MaterialStateProperty<_i5.Color?>? thumbColor,

    /// optionalParameters: {MaterialStateProperty<Color?>? trackColor} , default:none
    _i8.MaterialStateProperty<_i5.Color?>? trackColor,

    /// optionalParameters: {MaterialStateProperty<Color?>? trackOutlineColor} , default:none
    _i8.MaterialStateProperty<_i5.Color?>? trackOutlineColor,

    /// optionalParameters: {MaterialStateProperty<Icon?>? thumbIcon} , default:none
    _i8.MaterialStateProperty<_i9.Icon?>? thumbIcon,

    /// optionalParameters: {MaterialTapTargetSize? materialTapTargetSize} , default:none
    _i10.MaterialTapTargetSize? materialTapTargetSize,

    /// optionalParameters: {DragStartBehavior dragStartBehavior = DragStartBehavior.start} , default:processed=PrefixedIdentifierImpl
    _i11.DragStartBehavior dragStartBehavior = _i12.DragStartBehavior.start,

    /// optionalParameters: {MouseCursor? mouseCursor} , default:none
    _i13.MouseCursor? mouseCursor,

    /// optionalParameters: {MaterialStateProperty<Color?>? overlayColor} , default:none
    _i8.MaterialStateProperty<_i5.Color?>? overlayColor,

    /// optionalParameters: {double? splashRadius} , default:none
    double? splashRadius,

    /// optionalParameters: {FocusNode? focusNode} , default:none
    _i14.FocusNode? focusNode,

    /// optionalParameters: {void Function(bool)? onFocusChange} , default:none
    _i4.ValueChanged<bool>? onFocusChange,

    /// optionalParameters: {bool autofocus = false} , default:processed=BooleanLiteralImpl
    bool autofocus = false,

    /// optionalParameters: {Color? tileColor} , default:none
    _i5.Color? tileColor,

    /// optionalParameters: {Widget? title} , default:none
    _i15.Widget? title,

    /// optionalParameters: {Widget? subtitle} , default:none
    _i15.Widget? subtitle,

    /// optionalParameters: {bool isThreeLine = false} , default:processed=BooleanLiteralImpl
    bool isThreeLine = false,

    /// optionalParameters: {bool? dense} , default:none
    bool? dense,

    /// optionalParameters: {EdgeInsetsGeometry? contentPadding} , default:none
    _i16.EdgeInsetsGeometry? contentPadding,

    /// optionalParameters: {Widget? secondary} , default:none
    _i15.Widget? secondary,

    /// optionalParameters: {bool selected = false} , default:processed=BooleanLiteralImpl
    bool selected = false,

    /// optionalParameters: {ListTileControlAffinity controlAffinity = ListTileControlAffinity.platform} , default:processed=PrefixedIdentifierImpl
    _i17.ListTileControlAffinity controlAffinity = _i18.ListTileControlAffinity.platform,

    /// optionalParameters: {ShapeBorder? shape} , default:none
    _i19.ShapeBorder? shape,

    /// optionalParameters: {Color? selectedTileColor} , default:none
    _i5.Color? selectedTileColor,

    /// optionalParameters: {VisualDensity? visualDensity} , default:none
    _i10.VisualDensity? visualDensity,

    /// optionalParameters: {bool? enableFeedback} , default:none
    bool? enableFeedback,

    /// optionalParameters: {Color? hoverColor} , default:none
    _i5.Color? hoverColor,
  }) : super(
          key: key,
          value: value,
          onChanged: onChanged,
          activeColor: activeColor,
          activeTrackColor: activeTrackColor,
          inactiveThumbColor: inactiveThumbColor,
          inactiveTrackColor: inactiveTrackColor,
          activeThumbImage: activeThumbImage,
          onActiveThumbImageError: onActiveThumbImageError,
          inactiveThumbImage: inactiveThumbImage,
          onInactiveThumbImageError: onInactiveThumbImageError,
          thumbColor: thumbColor,
          trackColor: trackColor,
          trackOutlineColor: trackOutlineColor,
          thumbIcon: thumbIcon,
          materialTapTargetSize: materialTapTargetSize,
          dragStartBehavior: dragStartBehavior,
          mouseCursor: mouseCursor,
          overlayColor: overlayColor,
          splashRadius: splashRadius,
          focusNode: focusNode,
          onFocusChange: onFocusChange,
          autofocus: autofocus,
          tileColor: tileColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          contentPadding: contentPadding,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          shape: shape,
          selectedTileColor: selectedTileColor,
          visualDensity: visualDensity,
          enableFeedback: enableFeedback,
          hoverColor: hoverColor,
        ) {
    mateBuilderName = 'SwitchListTile';
    matePackageUrl = 'package:flutter/material.dart';
    mateBuilder = (p) => SwitchListTile$Mate(
          key: p.get('key').build(),
          value: p.get('value').build(),
          onChanged: p.get('onChanged').build(),
          activeColor: p.get('activeColor').build(),
          activeTrackColor: p.get('activeTrackColor').build(),
          inactiveThumbColor: p.get('inactiveThumbColor').build(),
          inactiveTrackColor: p.get('inactiveTrackColor').build(),
          activeThumbImage: p.get('activeThumbImage').build(),
          onActiveThumbImageError: p.get('onActiveThumbImageError').build(),
          inactiveThumbImage: p.get('inactiveThumbImage').build(),
          onInactiveThumbImageError: p.get('onInactiveThumbImageError').build(),
          thumbColor: p.get('thumbColor').build(),
          trackColor: p.get('trackColor').build(),
          trackOutlineColor: p.get('trackOutlineColor').build(),
          thumbIcon: p.get('thumbIcon').build(),
          materialTapTargetSize: p.get('materialTapTargetSize').build(),
          dragStartBehavior: p.get('dragStartBehavior').build(),
          mouseCursor: p.get('mouseCursor').build(),
          overlayColor: p.get('overlayColor').build(),
          splashRadius: p.get('splashRadius').build(),
          focusNode: p.get('focusNode').build(),
          onFocusChange: p.get('onFocusChange').build(),
          autofocus: p.get('autofocus').build(),
          tileColor: p.get('tileColor').build(),
          title: p.get('title').build(),
          subtitle: p.get('subtitle').build(),
          isThreeLine: p.get('isThreeLine').build(),
          dense: p.get('dense').build(),
          contentPadding: p.get('contentPadding').build(),
          secondary: p.get('secondary').build(),
          selected: p.get('selected').build(),
          controlAffinity: p.get('controlAffinity').build(),
          shape: p.get('shape').build(),
          selectedTileColor: p.get('selectedTileColor').build(),
          visualDensity: p.get('visualDensity').build(),
          enableFeedback: p.get('enableFeedback').build(),
          hoverColor: p.get('hoverColor').build(),
        );
    mateUse(
      'key',
      key,
      isNamed: true,
    );
    mateUse(
      'value',
      value,
      isNamed: true,
    );
    mateUse(
      'onChanged',
      onChanged,
      isNamed: true,
    );
    mateUse(
      'activeColor',
      activeColor,
      isNamed: true,
    );
    mateUse(
      'activeTrackColor',
      activeTrackColor,
      isNamed: true,
    );
    mateUse(
      'inactiveThumbColor',
      inactiveThumbColor,
      isNamed: true,
    );
    mateUse(
      'inactiveTrackColor',
      inactiveTrackColor,
      isNamed: true,
    );
    mateUse(
      'activeThumbImage',
      activeThumbImage,
      isNamed: true,
    );
    mateUse(
      'onActiveThumbImageError',
      onActiveThumbImageError,
      isNamed: true,
    );
    mateUse(
      'inactiveThumbImage',
      inactiveThumbImage,
      isNamed: true,
    );
    mateUse(
      'onInactiveThumbImageError',
      onInactiveThumbImageError,
      isNamed: true,
    );
    mateUse(
      'thumbColor',
      thumbColor,
      isNamed: true,
    );
    mateUse(
      'trackColor',
      trackColor,
      isNamed: true,
    );
    mateUse(
      'trackOutlineColor',
      trackOutlineColor,
      isNamed: true,
    );
    mateUse(
      'thumbIcon',
      thumbIcon,
      isNamed: true,
    );
    mateUse(
      'materialTapTargetSize',
      materialTapTargetSize,
      isNamed: true,
    );
    mateUse(
      'dragStartBehavior',
      dragStartBehavior,
      isNamed: true,
      defaultValue: _i12.DragStartBehavior.start,
    );
    mateUse(
      'mouseCursor',
      mouseCursor,
      isNamed: true,
    );
    mateUse(
      'overlayColor',
      overlayColor,
      isNamed: true,
    );
    mateUse(
      'splashRadius',
      splashRadius,
      isNamed: true,
    );
    mateUse(
      'focusNode',
      focusNode,
      isNamed: true,
    );
    mateUse(
      'onFocusChange',
      onFocusChange,
      isNamed: true,
    );
    mateUse(
      'autofocus',
      autofocus,
      isNamed: true,
      defaultValue: false,
    );
    mateUse(
      'tileColor',
      tileColor,
      isNamed: true,
    );
    mateUse(
      'title',
      title,
      isNamed: true,
    );
    mateUse(
      'subtitle',
      subtitle,
      isNamed: true,
    );
    mateUse(
      'isThreeLine',
      isThreeLine,
      isNamed: true,
      defaultValue: false,
    );
    mateUse(
      'dense',
      dense,
      isNamed: true,
    );
    mateUse(
      'contentPadding',
      contentPadding,
      isNamed: true,
    );
    mateUse(
      'secondary',
      secondary,
      isNamed: true,
    );
    mateUse(
      'selected',
      selected,
      isNamed: true,
      defaultValue: false,
    );
    mateUse(
      'controlAffinity',
      controlAffinity,
      isNamed: true,
      defaultValue: _i18.ListTileControlAffinity.platform,
    );
    mateUse(
      'shape',
      shape,
      isNamed: true,
    );
    mateUse(
      'selectedTileColor',
      selectedTileColor,
      isNamed: true,
    );
    mateUse(
      'visualDensity',
      visualDensity,
      isNamed: true,
    );
    mateUse(
      'enableFeedback',
      enableFeedback,
      isNamed: true,
    );
    mateUse(
      'hoverColor',
      hoverColor,
      isNamed: true,
    );
  }

  /// SwitchListTile SwitchListTile.adaptive({Key? key, required bool value, required void Function(bool)? onChanged, Color? activeColor, Color? activeTrackColor, Color? inactiveThumbColor, Color? inactiveTrackColor, ImageProvider<Object>? activeThumbImage, void Function(Object, StackTrace?)? onActiveThumbImageError, ImageProvider<Object>? inactiveThumbImage, void Function(Object, StackTrace?)? onInactiveThumbImageError, MaterialStateProperty<Color?>? thumbColor, MaterialStateProperty<Color?>? trackColor, MaterialStateProperty<Color?>? trackOutlineColor, MaterialStateProperty<Icon?>? thumbIcon, MaterialTapTargetSize? materialTapTargetSize, DragStartBehavior dragStartBehavior = DragStartBehavior.start, MouseCursor? mouseCursor, MaterialStateProperty<Color?>? overlayColor, double? splashRadius, FocusNode? focusNode, void Function(bool)? onFocusChange, bool autofocus = false, bool? applyCupertinoTheme, Color? tileColor, Widget? title, Widget? subtitle, bool isThreeLine = false, bool? dense, EdgeInsetsGeometry? contentPadding, Widget? secondary, bool selected = false, ListTileControlAffinity controlAffinity = ListTileControlAffinity.platform, ShapeBorder? shape, Color? selectedTileColor, VisualDensity? visualDensity, bool? enableFeedback, Color? hoverColor})
  SwitchListTile$Mate.adaptive({
    /// optionalParameters: {Key? key} , default:none
    _i3.Key? key,

    /// optionalParameters: {required bool value} , default:none
    required bool value,

    /// optionalParameters: {required void Function(bool)? onChanged} , default:none
    required _i4.ValueChanged<bool>? onChanged,

    /// optionalParameters: {Color? activeColor} , default:none
    _i5.Color? activeColor,

    /// optionalParameters: {Color? activeTrackColor} , default:none
    _i5.Color? activeTrackColor,

    /// optionalParameters: {Color? inactiveThumbColor} , default:none
    _i5.Color? inactiveThumbColor,

    /// optionalParameters: {Color? inactiveTrackColor} , default:none
    _i5.Color? inactiveTrackColor,

    /// optionalParameters: {ImageProvider<Object>? activeThumbImage} , default:none
    _i6.ImageProvider<Object>? activeThumbImage,

    /// optionalParameters: {void Function(Object, StackTrace?)? onActiveThumbImageError} , default:none
    _i7.ImageErrorListener? onActiveThumbImageError,

    /// optionalParameters: {ImageProvider<Object>? inactiveThumbImage} , default:none
    _i6.ImageProvider<Object>? inactiveThumbImage,

    /// optionalParameters: {void Function(Object, StackTrace?)? onInactiveThumbImageError} , default:none
    _i7.ImageErrorListener? onInactiveThumbImageError,

    /// optionalParameters: {MaterialStateProperty<Color?>? thumbColor} , default:none
    _i8.MaterialStateProperty<_i5.Color?>? thumbColor,

    /// optionalParameters: {MaterialStateProperty<Color?>? trackColor} , default:none
    _i8.MaterialStateProperty<_i5.Color?>? trackColor,

    /// optionalParameters: {MaterialStateProperty<Color?>? trackOutlineColor} , default:none
    _i8.MaterialStateProperty<_i5.Color?>? trackOutlineColor,

    /// optionalParameters: {MaterialStateProperty<Icon?>? thumbIcon} , default:none
    _i8.MaterialStateProperty<_i9.Icon?>? thumbIcon,

    /// optionalParameters: {MaterialTapTargetSize? materialTapTargetSize} , default:none
    _i10.MaterialTapTargetSize? materialTapTargetSize,

    /// optionalParameters: {DragStartBehavior dragStartBehavior = DragStartBehavior.start} , default:processed=PrefixedIdentifierImpl
    _i11.DragStartBehavior dragStartBehavior = _i12.DragStartBehavior.start,

    /// optionalParameters: {MouseCursor? mouseCursor} , default:none
    _i13.MouseCursor? mouseCursor,

    /// optionalParameters: {MaterialStateProperty<Color?>? overlayColor} , default:none
    _i8.MaterialStateProperty<_i5.Color?>? overlayColor,

    /// optionalParameters: {double? splashRadius} , default:none
    double? splashRadius,

    /// optionalParameters: {FocusNode? focusNode} , default:none
    _i14.FocusNode? focusNode,

    /// optionalParameters: {void Function(bool)? onFocusChange} , default:none
    _i4.ValueChanged<bool>? onFocusChange,

    /// optionalParameters: {bool autofocus = false} , default:processed=BooleanLiteralImpl
    bool autofocus = false,

    /// optionalParameters: {bool? applyCupertinoTheme} , default:none
    bool? applyCupertinoTheme,

    /// optionalParameters: {Color? tileColor} , default:none
    _i5.Color? tileColor,

    /// optionalParameters: {Widget? title} , default:none
    _i15.Widget? title,

    /// optionalParameters: {Widget? subtitle} , default:none
    _i15.Widget? subtitle,

    /// optionalParameters: {bool isThreeLine = false} , default:processed=BooleanLiteralImpl
    bool isThreeLine = false,

    /// optionalParameters: {bool? dense} , default:none
    bool? dense,

    /// optionalParameters: {EdgeInsetsGeometry? contentPadding} , default:none
    _i16.EdgeInsetsGeometry? contentPadding,

    /// optionalParameters: {Widget? secondary} , default:none
    _i15.Widget? secondary,

    /// optionalParameters: {bool selected = false} , default:processed=BooleanLiteralImpl
    bool selected = false,

    /// optionalParameters: {ListTileControlAffinity controlAffinity = ListTileControlAffinity.platform} , default:processed=PrefixedIdentifierImpl
    _i17.ListTileControlAffinity controlAffinity = _i18.ListTileControlAffinity.platform,

    /// optionalParameters: {ShapeBorder? shape} , default:none
    _i19.ShapeBorder? shape,

    /// optionalParameters: {Color? selectedTileColor} , default:none
    _i5.Color? selectedTileColor,

    /// optionalParameters: {VisualDensity? visualDensity} , default:none
    _i10.VisualDensity? visualDensity,

    /// optionalParameters: {bool? enableFeedback} , default:none
    bool? enableFeedback,

    /// optionalParameters: {Color? hoverColor} , default:none
    _i5.Color? hoverColor,
  }) : super.adaptive(
          key: key,
          value: value,
          onChanged: onChanged,
          activeColor: activeColor,
          activeTrackColor: activeTrackColor,
          inactiveThumbColor: inactiveThumbColor,
          inactiveTrackColor: inactiveTrackColor,
          activeThumbImage: activeThumbImage,
          onActiveThumbImageError: onActiveThumbImageError,
          inactiveThumbImage: inactiveThumbImage,
          onInactiveThumbImageError: onInactiveThumbImageError,
          thumbColor: thumbColor,
          trackColor: trackColor,
          trackOutlineColor: trackOutlineColor,
          thumbIcon: thumbIcon,
          materialTapTargetSize: materialTapTargetSize,
          dragStartBehavior: dragStartBehavior,
          mouseCursor: mouseCursor,
          overlayColor: overlayColor,
          splashRadius: splashRadius,
          focusNode: focusNode,
          onFocusChange: onFocusChange,
          autofocus: autofocus,
          applyCupertinoTheme: applyCupertinoTheme,
          tileColor: tileColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          contentPadding: contentPadding,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          shape: shape,
          selectedTileColor: selectedTileColor,
          visualDensity: visualDensity,
          enableFeedback: enableFeedback,
          hoverColor: hoverColor,
        ) {
    mateBuilderName = 'SwitchListTile.adaptive';
    matePackageUrl = 'package:flutter/material.dart';
    mateBuilder = (p) => SwitchListTile$Mate.adaptive(
          key: p.get('key').build(),
          value: p.get('value').build(),
          onChanged: p.get('onChanged').build(),
          activeColor: p.get('activeColor').build(),
          activeTrackColor: p.get('activeTrackColor').build(),
          inactiveThumbColor: p.get('inactiveThumbColor').build(),
          inactiveTrackColor: p.get('inactiveTrackColor').build(),
          activeThumbImage: p.get('activeThumbImage').build(),
          onActiveThumbImageError: p.get('onActiveThumbImageError').build(),
          inactiveThumbImage: p.get('inactiveThumbImage').build(),
          onInactiveThumbImageError: p.get('onInactiveThumbImageError').build(),
          thumbColor: p.get('thumbColor').build(),
          trackColor: p.get('trackColor').build(),
          trackOutlineColor: p.get('trackOutlineColor').build(),
          thumbIcon: p.get('thumbIcon').build(),
          materialTapTargetSize: p.get('materialTapTargetSize').build(),
          dragStartBehavior: p.get('dragStartBehavior').build(),
          mouseCursor: p.get('mouseCursor').build(),
          overlayColor: p.get('overlayColor').build(),
          splashRadius: p.get('splashRadius').build(),
          focusNode: p.get('focusNode').build(),
          onFocusChange: p.get('onFocusChange').build(),
          autofocus: p.get('autofocus').build(),
          applyCupertinoTheme: p.get('applyCupertinoTheme').build(),
          tileColor: p.get('tileColor').build(),
          title: p.get('title').build(),
          subtitle: p.get('subtitle').build(),
          isThreeLine: p.get('isThreeLine').build(),
          dense: p.get('dense').build(),
          contentPadding: p.get('contentPadding').build(),
          secondary: p.get('secondary').build(),
          selected: p.get('selected').build(),
          controlAffinity: p.get('controlAffinity').build(),
          shape: p.get('shape').build(),
          selectedTileColor: p.get('selectedTileColor').build(),
          visualDensity: p.get('visualDensity').build(),
          enableFeedback: p.get('enableFeedback').build(),
          hoverColor: p.get('hoverColor').build(),
        );
    mateUse(
      'key',
      key,
      isNamed: true,
    );
    mateUse(
      'value',
      value,
      isNamed: true,
    );
    mateUse(
      'onChanged',
      onChanged,
      isNamed: true,
    );
    mateUse(
      'activeColor',
      activeColor,
      isNamed: true,
    );
    mateUse(
      'activeTrackColor',
      activeTrackColor,
      isNamed: true,
    );
    mateUse(
      'inactiveThumbColor',
      inactiveThumbColor,
      isNamed: true,
    );
    mateUse(
      'inactiveTrackColor',
      inactiveTrackColor,
      isNamed: true,
    );
    mateUse(
      'activeThumbImage',
      activeThumbImage,
      isNamed: true,
    );
    mateUse(
      'onActiveThumbImageError',
      onActiveThumbImageError,
      isNamed: true,
    );
    mateUse(
      'inactiveThumbImage',
      inactiveThumbImage,
      isNamed: true,
    );
    mateUse(
      'onInactiveThumbImageError',
      onInactiveThumbImageError,
      isNamed: true,
    );
    mateUse(
      'thumbColor',
      thumbColor,
      isNamed: true,
    );
    mateUse(
      'trackColor',
      trackColor,
      isNamed: true,
    );
    mateUse(
      'trackOutlineColor',
      trackOutlineColor,
      isNamed: true,
    );
    mateUse(
      'thumbIcon',
      thumbIcon,
      isNamed: true,
    );
    mateUse(
      'materialTapTargetSize',
      materialTapTargetSize,
      isNamed: true,
    );
    mateUse(
      'dragStartBehavior',
      dragStartBehavior,
      isNamed: true,
      defaultValue: _i12.DragStartBehavior.start,
    );
    mateUse(
      'mouseCursor',
      mouseCursor,
      isNamed: true,
    );
    mateUse(
      'overlayColor',
      overlayColor,
      isNamed: true,
    );
    mateUse(
      'splashRadius',
      splashRadius,
      isNamed: true,
    );
    mateUse(
      'focusNode',
      focusNode,
      isNamed: true,
    );
    mateUse(
      'onFocusChange',
      onFocusChange,
      isNamed: true,
    );
    mateUse(
      'autofocus',
      autofocus,
      isNamed: true,
      defaultValue: false,
    );
    mateUse(
      'applyCupertinoTheme',
      applyCupertinoTheme,
      isNamed: true,
    );
    mateUse(
      'tileColor',
      tileColor,
      isNamed: true,
    );
    mateUse(
      'title',
      title,
      isNamed: true,
    );
    mateUse(
      'subtitle',
      subtitle,
      isNamed: true,
    );
    mateUse(
      'isThreeLine',
      isThreeLine,
      isNamed: true,
      defaultValue: false,
    );
    mateUse(
      'dense',
      dense,
      isNamed: true,
    );
    mateUse(
      'contentPadding',
      contentPadding,
      isNamed: true,
    );
    mateUse(
      'secondary',
      secondary,
      isNamed: true,
    );
    mateUse(
      'selected',
      selected,
      isNamed: true,
      defaultValue: false,
    );
    mateUse(
      'controlAffinity',
      controlAffinity,
      isNamed: true,
      defaultValue: _i18.ListTileControlAffinity.platform,
    );
    mateUse(
      'shape',
      shape,
      isNamed: true,
    );
    mateUse(
      'selectedTileColor',
      selectedTileColor,
      isNamed: true,
    );
    mateUse(
      'visualDensity',
      visualDensity,
      isNamed: true,
    );
    mateUse(
      'enableFeedback',
      enableFeedback,
      isNamed: true,
    );
    mateUse(
      'hoverColor',
      hoverColor,
      isNamed: true,
    );
  }
}
