// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/material/time_picker_theme.dart';
import 'package:note/mate.dart';
import 'dart:ui';
import 'package:flutter/src/material/button_style.dart';
import 'package:flutter/src/painting/borders.dart';
import 'package:flutter/src/painting/text_style.dart';
import 'dart:core';
import 'package:flutter/src/material/input_decorator.dart';
import 'package:flutter/src/painting/edge_insets.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';

/// class TimePickerThemeData with Diagnosticable
class TimePickerThemeData$Mate extends TimePickerThemeData with Mate {
  /// TimePickerThemeData TimePickerThemeData({Color? backgroundColor, ButtonStyle? cancelButtonStyle, ButtonStyle? confirmButtonStyle, BorderSide? dayPeriodBorderSide, Color? dayPeriodColor, OutlinedBorder? dayPeriodShape, Color? dayPeriodTextColor, TextStyle? dayPeriodTextStyle, Color? dialBackgroundColor, Color? dialHandColor, Color? dialTextColor, TextStyle? dialTextStyle, double? elevation, Color? entryModeIconColor, TextStyle? helpTextStyle, Color? hourMinuteColor, ShapeBorder? hourMinuteShape, Color? hourMinuteTextColor, TextStyle? hourMinuteTextStyle, InputDecorationTheme? inputDecorationTheme, EdgeInsetsGeometry? padding, ShapeBorder? shape})
  TimePickerThemeData$Mate({
    /// optionalParameters: {Color? backgroundColor} , defaultValue:none
    Color? backgroundColor,

    /// optionalParameters: {ButtonStyle? cancelButtonStyle} , defaultValue:none
    ButtonStyle? cancelButtonStyle,

    /// optionalParameters: {ButtonStyle? confirmButtonStyle} , defaultValue:none
    ButtonStyle? confirmButtonStyle,

    /// optionalParameters: {BorderSide? dayPeriodBorderSide} , defaultValue:none
    BorderSide? dayPeriodBorderSide,

    /// optionalParameters: {Color? dayPeriodColor} , defaultValue:none
    Color? dayPeriodColor,

    /// optionalParameters: {OutlinedBorder? dayPeriodShape} , defaultValue:none
    OutlinedBorder? dayPeriodShape,

    /// optionalParameters: {Color? dayPeriodTextColor} , defaultValue:none
    Color? dayPeriodTextColor,

    /// optionalParameters: {TextStyle? dayPeriodTextStyle} , defaultValue:none
    TextStyle? dayPeriodTextStyle,

    /// optionalParameters: {Color? dialBackgroundColor} , defaultValue:none
    Color? dialBackgroundColor,

    /// optionalParameters: {Color? dialHandColor} , defaultValue:none
    Color? dialHandColor,

    /// optionalParameters: {Color? dialTextColor} , defaultValue:none
    Color? dialTextColor,

    /// optionalParameters: {TextStyle? dialTextStyle} , defaultValue:none
    TextStyle? dialTextStyle,

    /// optionalParameters: {double? elevation} , defaultValue:none
    double? elevation,

    /// optionalParameters: {Color? entryModeIconColor} , defaultValue:none
    Color? entryModeIconColor,

    /// optionalParameters: {TextStyle? helpTextStyle} , defaultValue:none
    TextStyle? helpTextStyle,

    /// optionalParameters: {Color? hourMinuteColor} , defaultValue:none
    Color? hourMinuteColor,

    /// optionalParameters: {ShapeBorder? hourMinuteShape} , defaultValue:none
    ShapeBorder? hourMinuteShape,

    /// optionalParameters: {Color? hourMinuteTextColor} , defaultValue:none
    Color? hourMinuteTextColor,

    /// optionalParameters: {TextStyle? hourMinuteTextStyle} , defaultValue:none
    TextStyle? hourMinuteTextStyle,

    /// optionalParameters: {InputDecorationTheme? inputDecorationTheme} , defaultValue:none
    InputDecorationTheme? inputDecorationTheme,

    /// optionalParameters: {EdgeInsetsGeometry? padding} , defaultValue:none
    EdgeInsetsGeometry? padding,

    /// optionalParameters: {ShapeBorder? shape} , defaultValue:none
    ShapeBorder? shape,
  }) : super(
          backgroundColor: backgroundColor,
          cancelButtonStyle: cancelButtonStyle,
          confirmButtonStyle: confirmButtonStyle,
          dayPeriodBorderSide: dayPeriodBorderSide,
          dayPeriodColor: dayPeriodColor,
          dayPeriodShape: dayPeriodShape,
          dayPeriodTextColor: dayPeriodTextColor,
          dayPeriodTextStyle: dayPeriodTextStyle,
          dialBackgroundColor: dialBackgroundColor,
          dialHandColor: dialHandColor,
          dialTextColor: dialTextColor,
          dialTextStyle: dialTextStyle,
          elevation: elevation,
          entryModeIconColor: entryModeIconColor,
          helpTextStyle: helpTextStyle,
          hourMinuteColor: hourMinuteColor,
          hourMinuteShape: hourMinuteShape,
          hourMinuteTextColor: hourMinuteTextColor,
          hourMinuteTextStyle: hourMinuteTextStyle,
          inputDecorationTheme: inputDecorationTheme,
          padding: padding,
          shape: shape,
        ) {
    mateCreateName = 'TimePickerThemeData';
    matePackageUrl = 'package:flutter/material.dart';
    mateBuilder = (p) => TimePickerThemeData$Mate(
          backgroundColor: p.get('backgroundColor').build(),
          cancelButtonStyle: p.get('cancelButtonStyle').build(),
          confirmButtonStyle: p.get('confirmButtonStyle').build(),
          dayPeriodBorderSide: p.get('dayPeriodBorderSide').build(),
          dayPeriodColor: p.get('dayPeriodColor').build(),
          dayPeriodShape: p.get('dayPeriodShape').build(),
          dayPeriodTextColor: p.get('dayPeriodTextColor').build(),
          dayPeriodTextStyle: p.get('dayPeriodTextStyle').build(),
          dialBackgroundColor: p.get('dialBackgroundColor').build(),
          dialHandColor: p.get('dialHandColor').build(),
          dialTextColor: p.get('dialTextColor').build(),
          dialTextStyle: p.get('dialTextStyle').build(),
          elevation: p.get('elevation').build(),
          entryModeIconColor: p.get('entryModeIconColor').build(),
          helpTextStyle: p.get('helpTextStyle').build(),
          hourMinuteColor: p.get('hourMinuteColor').build(),
          hourMinuteShape: p.get('hourMinuteShape').build(),
          hourMinuteTextColor: p.get('hourMinuteTextColor').build(),
          hourMinuteTextStyle: p.get('hourMinuteTextStyle').build(),
          inputDecorationTheme: p.get('inputDecorationTheme').build(),
          padding: p.get('padding').build(),
          shape: p.get('shape').build(),
        );
    mateUse('backgroundColor', backgroundColor);
    mateUse('cancelButtonStyle', cancelButtonStyle);
    mateUse('confirmButtonStyle', confirmButtonStyle);
    mateUse('dayPeriodBorderSide', dayPeriodBorderSide);
    mateUse('dayPeriodColor', dayPeriodColor);
    mateUse('dayPeriodShape', dayPeriodShape);
    mateUse('dayPeriodTextColor', dayPeriodTextColor);
    mateUse('dayPeriodTextStyle', dayPeriodTextStyle);
    mateUse('dialBackgroundColor', dialBackgroundColor);
    mateUse('dialHandColor', dialHandColor);
    mateUse('dialTextColor', dialTextColor);
    mateUse('dialTextStyle', dialTextStyle);
    mateUse('elevation', elevation);
    mateUse('entryModeIconColor', entryModeIconColor);
    mateUse('helpTextStyle', helpTextStyle);
    mateUse('hourMinuteColor', hourMinuteColor);
    mateUse('hourMinuteShape', hourMinuteShape);
    mateUse('hourMinuteTextColor', hourMinuteTextColor);
    mateUse('hourMinuteTextStyle', hourMinuteTextStyle);
    mateUse('inputDecorationTheme', inputDecorationTheme);
    mateUse('padding', padding);
    mateUse('shape', shape);
  }
}

/// class TimePickerTheme extends InheritedTheme
class TimePickerTheme$Mate extends TimePickerTheme with Mate {
  /// TimePickerTheme TimePickerTheme({Key? key, required TimePickerThemeData data, required Widget child})
  TimePickerTheme$Mate({
    /// optionalParameters: {Key? key} , defaultValue:none
    Key? key,

    /// optionalParameters: {required TimePickerThemeData data} , defaultValue:none
    required TimePickerThemeData data,

    /// optionalParameters: {required Widget child} , defaultValue:none
    required Widget child,
  }) : super(
          key: key,
          data: data,
          child: child,
        ) {
    mateCreateName = 'TimePickerTheme';
    matePackageUrl = 'package:flutter/material.dart';
    mateBuilder = (p) => TimePickerTheme$Mate(
          key: p.get('key').build(),
          data: p.get('data').build(),
          child: p.get('child').build(),
        );
    mateUse('key', key);
    mateUse('data', data);
    mateUse('child', child);
  }
}
