// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/painting/flutter_logo.dart';
import 'dart:ui';
import 'package:flutter/src/painting/edge_insets.dart';
import 'package:note/mate.dart';

/// class FlutterLogoDecoration extends Decoration
class FlutterLogoDecoration$Mate extends FlutterLogoDecoration with Mate<FlutterLogoDecoration$Mate> {
  /// FlutterLogoDecoration FlutterLogoDecoration({Color textColor = const Color(0xFF757575), FlutterLogoStyle style = FlutterLogoStyle.markOnly, EdgeInsets margin = EdgeInsets.zero})
  FlutterLogoDecoration$Mate({
    /// optionalParameters: {Color textColor = const Color(0xFF757575)} , hasDefaultValue:true, defaultValueCode:const Color(0xFF757575)
    required Color textColor,

    /// optionalParameters: {FlutterLogoStyle style = FlutterLogoStyle.markOnly} , hasDefaultValue:true, defaultValueCode:FlutterLogoStyle.markOnly
    required FlutterLogoStyle style,

    /// optionalParameters: {EdgeInsets margin = EdgeInsets.zero} , hasDefaultValue:true, defaultValueCode:EdgeInsets.zero
    required EdgeInsets margin,
  }) : super(
          textColor: textColor,
          style: style,
          margin: margin,
        ) {
    mateParams = ObjectParam(
      init: this,
      builder: (p) => FlutterLogoDecoration$Mate(
        textColor: p.get('textColor').build(),
        style: p.get('style').build(),
        margin: p.get('margin').build(),
      ),
    );
    mateParams.put('textColor', textColor);
    mateParams.put('style', style);
    mateParams.put('margin', margin);
  }
}
