#!/usr/bin/env bash

# On Mac OS, readlink -f doesn't work, so use._real_path get the real path of the file
_real_path() (
  cd "$(dirname "$1")"
  file="$PWD/$(basename "$1")"
  while [[ -L "$file" ]]; do
    file="$(readlink "$file")"
    cd -P "$(dirname "$file")"
    file="$PWD/$(basename "$file")"
  done
  echo "$file"
)
SCRIPT_PATH="$(_real_path "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
SCRIPT_FILE="$(basename "$SCRIPT_PATH")"

# include common script
source "$SCRIPT_DIR/vendor/bake.bash"

##########################################
# app cmd script
# 应用的命令脚本
##########################################

bake.cmd --cmd _root \
             --usage "./$SCRIPT_FILE [cmd] [opts] [args...]" \
             --summary "flutter-note build cli." \
             --help "$( cat <<-EOF

 ___  _        _    _                    _  _       _
| __|| | _  _ | |_ | |_  ___  _ _       | \| | ___ | |_  ___
| _| | || || ||  _||  _|/ -_)| '_|      | .  |/ _ \|  _|/ -_)
|_|  |_| \_._| \__| \__|\___||_|        |_|\_|\___/ \__|\___|

flutter-note build tools.
https://github.com/chen56/note

Examples:
 ./${SCRIPT_FILE}                          # same as  './${SCRIPT_FILE} -h'
 ./${SCRIPT_FILE} -h                       # show all commands help
 ./${SCRIPT_FILE} -h --debug               # show all commands help , include internal function

 ./${SCRIPT_FILE}  test                    # test all projects
 ./${SCRIPT_FILE}  build                   # defalut build == flutter build web --web-renderer html
 ./${SCRIPT_FILE}  preview                 # defalut preview == run server at web build
 ./${SCRIPT_FILE}  test                    # test all projects

 ./${SCRIPT_FILE}  p -h                    # show all mono project commands help
 ./${SCRIPT_FILE}  p note pwd              # run "pwd" on note project dir
 ./${SCRIPT_FILE}  p all pwd               # run "pwd" on all mono projects
 ./${SCRIPT_FILE}  p all flutter pub get   # run "flutter pub get" on all mono projects

EOF
  )"


# run一条命令，先print上下文信息，再执行
# Usage: run <some cmd>
# Example:
# ------------------------------------
# $ ./bake run pwd
# /Users/x/git/younpc/bake:733 -> bake.go() ▶︎【pwd】
# /Users/x/git/younpc
# ------------------------------------
run() {
  local caller_line=$(caller 0 | awk '{print $1}')
  local project
  project=$(basename "$PWD")
  #  [[ "$PWD" == "$SCRIPT_DIR" ]] && project="_root"
  echo "$SCRIPT_PATH:$caller_line -> ${FUNCNAME[1]} ▶︎【$@】"
  "$@"
  return $?
}


#   flutter_note flutter create --platforms=macos .
install() {
  run git lfs install
}

bake.cmd --cmd p --summary "<mono>  project set" --usage "Usage: ./$SCRIPT_FILE p <sub_cmd>"
#p(){ echo "use './$SCRIPT_FILE p -h' see sub commands, there are all projects "; }

bake.cmd --cmd p.all --summary "<mono>  run cmd on all mono project" --usage "Usage: ./$SCRIPT_FILE all [any command]"
p.all() {
  #       目录中有"pubspec.yaml"的，认为是flutter项目
  #        for project in $( find . -name pubspec.yaml | sed s/pubspec.yaml$//g ) ; do
  #          # 用括号()开启子进程执行，可以不影响当前进程的环境
  #          ( cd "$project" ;  run "$@" ; )
  #        done
  (cd learn_dart && run "$@")
  (cd note && run "$@")
  (cd mate_flutter && run "$@")
  (cd mate && run "$@")
  (cd note_test && run "$@")
  (cd note_tools && run "$@")
  (cd spaces/flutter_note && run "$@")
}

p.note() (cd note && run "$@")
p.flutter_note() (cd spaces/flutter_note && run "$@")
p.mate() (cd mate && run "$@")
p.mate_flutter() (cd mate_flutter && run "$@")
p.note_test() (cd note_test && run "$@")
p.note_tools() (cd note_tools && run "$@")

get() { run p.all flutter pub get; }

test() { ./test/bake2_test.bash test ; run p.all flutter test ;}
test.bake() { ./test/bake2_test.bash test ; }

# get ip only work on macos
#   shellcheck disable=SC2155
#   local ip=$(ifconfig -l | xargs -n1 ipconfig getifaddr) || true
run.web() { p.flutter_note flutter run --web-port 8888 --web-renderer html --device-id chrome "$@"; }
run.macos() { p.flutter_note flutter run --device-id macos "$@"; }

# skwasm无法运行
build.macos() { run p.flutter_note flutter build macos -v --release --tree-shake-icons "$@";  }
build.web_skwasm() {    p.flutter_note flutter build web -v --release --tree-shake-icons --web-renderer skwasm "$@" ; }
build.web_canvaskit() { p.flutter_note flutter build web -v --release --tree-shake-icons --web-renderer canvaskit "$@" ; }
build() {      p.flutter_note flutter build web -v --release --tree-shake-icons --web-renderer html "$@" ; }

  #   http-server 不支持base href设置，所以单独build,并设置base-href为"/",而github-pages的base-href必须是repository名
  #   	npx http-server ./flutter_note/build/web --port 8000
    # flutter pub global activate dhttpd
    # run p.flutter_note dhttpd --path ./build/web --port 8080 '--headers=Cross-Origin-Embedder-Policy=credentialless;Cross-Origin-Opener-Policy=same-origin'
preview.web() { run p.flutter_note deno run --allow-env --allow-read --allow-sys --allow-net npm:http-server ./build/web --port 8000 -g --brotli; }
preview.macos() (  run p.flutter_note open build/macos/Build/Products/Release/flutter_note.app ; )

#   http-server 不支持base href设置，所以单独build,并设置base-href为"/",而github-pages的base-href必须是repository名
#    build "$@"
#   	npx http-server ./flutter_note/build/web --port 8000
web.serve() {     run p.flutter_note deno run --allow-env --allow-read --allow-sys --allow-net npm:http-server ./build/web --port 8000 -g --brotli ;}

clean() { p.all flutter clean; rm -rf build;}

gen.all() {  gen.notes;  } #  gen.mate;不再用了
gen.notes() { run p.flutter_note dart run tools/gen.dart;        run p.flutter_note flutter pub get; }
gen.mate() (  run p.mate_flutter dart run  tools/gen_mates.dart; run p.mate_flutter dart run  tools/gen_mate_icons.dart ; )
gen.clean() { run rm -f p.flutter_note/lib/pages.g.dart;         run rm -rf mate_flutter/lib;  }

docker.build() (    run docker build --progress plain --tag younpc/note:latest . ; run mkdir -p build/flutter_note/web; run sh -c "docker run --rm --workdir /usr/share/nginx/html/note younpc/note tar cf - ./ | ( cd build/flutter_note/web; tar xf -)";)
docker.run() {      run echo "note preview http://localhost:8888/note/"; run docker run --rm --name note -p 8888:80 -u root:root younpc/note;}
docker.preview() {  run docker build --progress plain --build-arg test=off --tag younpc/note:latest . ; docker.run; }
docker.debug() {    run docker run -v $PWD:/home/flutter/note --workdir /home/flutter/note --rm -it fischerscode/flutter:3.10.0-1.3.pre bash ; }
docker.push() {     docker image push younpc/note:latest ; }


####################################################
# app entry script & _root cmd
####################################################
bake.go "$@"

