#!/usr/bin/env bash
set -o errtrace # -E trap inherited in sub script
set -o errexit # -e
set -o functrace # -T If set, any trap on DEBUG and RETURN are inherited by shell functions
set -o pipefail  # default pipeline status==last command status, If set, status=any command fail
#set -o nounset # -u: don't use it ,it is crazy, 1.bash version is diff Behavior 2.we need like this: ${arr[@]+"${arr[@]}"}
# todo trap exit and kill all subprocess


# bake == (bash)ake == 去make的bash工具
# v0.2.20230515 目前仅在macos上跑过
# ------------------------------------------------------------------------------
# bake 是个简单的自建命令工具，以替代Makefile的子命令功能
# make工具的主要特点是处理文件依赖进行增量编译，但flutter、golang、java、js项目的build工具
# 太厉害了，这几年唯一还在用Makefile的理由就是他的子命令机制: "make build"、
# "make run", 可以方便的自定义单一入口的父子命令，但Makefile本身的语法套路也很复杂，
# 很多批处理还是要靠bash, 这就尴尬了，工具太多，麻烦！本脚本尝试彻底摆脱使用Makefile。
# 经尝试，代码很少啊 ，核心公共代码百十行啊，还主要是提取显示子命令帮助的，功能足够了：
#   ./bake       # 列子命令看帮助，
#   ./bake build # 子命令
#   ./bake run   # 子命令
# bake命令规则：
# 1. 定义以斜杠"/"为前缀的function作为子命令，/build、/run、/assets/list、
#    表示命令的其父子关系，执行时去掉斜杠/, 构成父子命令：./bake assets list -x -y -z
# 2. 除bash外，尽量不依赖其他工具，包括linux coreutils,以便跨平台更简单
# 搞docker那样的命令树，应该也不难，目前和make一样只支持一级子命令，暂时够用。
# ref
# https://pub.dev/documentation/args/latest/args/ArgParser-class.html
# https://github.com/spf13/pflag/blob/master/string_array.go
# https://oclif.io/docs/flags
# ------------------------------------------------------------------------------

if ((BASH_VERSINFO[0] < 4)); then
  echo "Error: 都2082年了，您的bash还是这个版本(BASH_VERSINFO: ${BASH_VERSINFO[*]})，请安装bash 4+ 后重启terminal:
  apt install bash  # ubuntu
  brew install bash # mac"
  exit 1
fi

# copy from flutter
# ----------------------
# On Mac OS, readlink -f doesn't work, so bake.readlink traverses the path one
# link at a time, and then cds into the link destination and find out where it
# ends up.
# The function is enclosed in a subshell to avoid changing the working directory
# of the caller.
function _readlink() (
  cd -P "$(dirname -- "$1")"
  file="$PWD/$(basename -- "$1")"
  while [[ -L "$file" ]]; do
    cd -P "$(dirname -- "$file")"
    file="$(readlink -- "$file")"
    cd -P "$(dirname -- "$file")"
    file="$PWD/$(basename -- "$file")"
  done
  echo "$file"
)

function doctor()(
  echo '# doctor'
  echo '## _cmdTree'
  for key in "${!_cmdTree[@]}"; do
    echo "cmd  - $key=${_cmdTree[$key]:0:100}"
  done
  echo '## _data'
  for key in "${!_data[@]}"; do
    echo "data - $key=${_data[$key]:0:100}"
  done
)


_on_error() {
  echo "trapped an error: ↑ , trace: ↓" >&2
  _stack_frame
}
# Usage: _stack_frame
_stack_frame() {
  local i=0
  local stackInfo
  while true; do
    stackInfo=$(caller $i 2>&1 && true) && true
    if [[ $? != 0 ]]; then break; fi

    # parse
    # 97 test_bake.split ./test/bake2_test.bash
    local no func file;
    IFS=' ' read -r no func file <<< "$stackInfo"

    # clickable stack:
    # /Users/c/git/younpc/note/test/bake2_test.bash:38 bake.test.runTest()
    printf "%s\n" "$(_readlink $file):$no $func()" >&2

    i=$((i + 1))
  done
}
# Add the error catch first
#
trap " set +x; _on_error " ERR

##########################################
# bake common script
##########################################
BAKE_PATH="$(_readlink "${BASH_SOURCE[0]}")"
BAKE_DIR="$(dirname "$BAKE_PATH")"
BAKE_FILE="$(basename "$BAKE_PATH")"

# set workdir
cd "${BAKE_DIR}"

# Simulating object-oriented data structures with flat associative arrays
# opts define:
#_root/opts/help/abbr=h
#_root/opts/help/cmd=_root
#_root/opts/help/name=help
#_root/opts/help/optHelp=print help, show all commands
#_root/opts/help/type=bool
#_root/opts/verbose/abbr=v
#_root/opts/verbose/cmd=_root
#_root/opts/verbose/name=verbose
#_root/opts/verbose/optHelp=verbose, show more info, more hidden commands
#_root/opts/verbose/type=bool
#bake.opt.add/opts/abbr/name=abbr
#bake.opt.add/opts/abbr/type=string
#bake.opt.add/opts/cmd/name=cmd
#bake.opt.add/opts/cmd/type=string
#bake.opt.add/opts/name/name=name
#bake.opt.add/opts/name/required=true
#bake.opt.add/opts/name/type=string
#bake.opt.add/opts/optHelp/name=optHelp
#bake.opt.add/opts/optHelp/type=string
#bake.opt.add/opts/type/name=type
#bake.opt.add/opts/type/type=string
# parsed opts value:
#  _data[_root/opts/verbose/value]=true
#  _data[pub.get/opts/notes/value/0]="..lib/note.page"
#  _data[pub.get/opts/notes/value/1]="./lib/a/note.page"
# save all other data
declare -A _data

# only save all commands, we use it to build command tree
# it is cache data from _data
declare -A _cmdTree

TYPE_CMD="type:cmd"

##########################################
# bake common function
##########################################
# Usage: bake.data.children <dataPath>
#   return <dataPath> children name
bake.data.children() (
  path="$1"
  # ${!_data[@]}: get all array keys
  for key in "${!_data[@]}"; do
    # if start $path
    if [[ "$key" == "$path"* ]]; then
      # https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
      # remove prefix : key:build/opts/dir/type/x leftPathToBeCut:build/opts => dir/type/x
      child=$(bake.str.cutLeft "$key" "$path/")
      # remove suffix:  dir/type/x => dir
#      child=${child%%/*}
      child=$(bake.path.first "$child" "/")
      printf '%s\n' "$child"
    fi
  done | sort -u
)
function bake.cmd.list()(
  contextCmd=$1
#  showList=()
#  maxLengthOfCmd=0
  for child in $(bake.data.children "$contextCmd"); do
    [[ "$contextCmd" == "" ]] && key="$child" || key="$contextCmd/$child"
    if   [[ "$key"              == bake*      ]]; then continue; fi
    if   [[ "$key"              == @fields*   ]]; then continue; fi
    if   [[ "$key"              == _*         ]]; then continue; fi
    if   [[ "${_cmdTree[$key]}" != "type:cmd" ]]; then continue; fi
    echo "$key : ${_cmdTree[$key.@fields.summary]}"
  done
)

# Usage: bake.cmd.register
# ensure all cmd register
function bake.cmd.register() {
     local functionName
     while IFS=$'\n' read -r functionName ; do
      if [[ "$functionName" == */*  ]]; then
        echo "error: function $functionName() can not contains '/' " >&2 && return 1
      fi
      local traverseUpPath
      for traverseUpPath in $(bake.cmd.list_up "$functionName");do
        _cmdTree["$traverseUpPath"]="PARENT_CMD_NOT_FUNC"
      done
      _cmdTree[$functionName]=$functionName

      # list all function name
      # declare -F | awk {'print $3'} == compgen -A function
      # declare -f func1  -> func1
      # declare -fx func2 -> func2
    done <<< "$(compgen -A function)"
}


# Usage: bake.split <str> [delimiter:default /]
bake.split() {
  local str=$1 delimiter=${2:-/};
#  # use <() process-substitution
#  # don't use <<< "" its add newline
  local arr
  readarray -t arr < <(printf '%s' "${str//$delimiter/$'\n'}")
  printf '%s\n' "${arr[@]}"
}

# Usage: bake.path.dirname <str> [delimiter:default /]
# similar command dirname, but
#     dirname root is ".", only work with "/"
#     bake.path.dirname root is "" , can set delimiter
# bake.path.dirname a.b.c .    => a.b
bake.path.dirname(){
  local pathLikeStr="$1" delimiter="${2:-/}"
  if [[ "$pathLikeStr" != *"$delimiter"* ]]; then printf '' ; return ; fi
  printf '%s' "${pathLikeStr%$delimiter*}"
}
# Usage: bake.path.first <str> [delimiter:default /]
# bake.path.first a.b.c .    => a
bake.path.first(){
  local pathLikeStr="$1" delimiter="${2:-/}"
  # if /a/b/c , call :bake.path.first a/b/c /
  if [[ "$pathLikeStr" == "$delimiter"* ]] ; then
    local removeDelim; removeDelim=$(bake.str.cutLeft "$pathLikeStr" "$delimiter")
    printf "$delimiter$(bake.path.first "$removeDelim" "$delimiter" )"
  else # a/b/c
    printf "${pathLikeStr%%$delimiter*}"
  fi
}
# similar command basename
# Usage: bake.path.basename <str> [delimiter:default /]
bake.path.basename(){
  local pathLikeStr="$1" delimiter="${2:-/}"
  # ${1##*/}  => ## left remove until last "/"
  printf "${pathLikeStr##*$delimiter}";
}
# Usage: bake.cmd.list_up <cmd>
# sample: bake.cmd.list_up a.b      => "a.b\n", "a\n", "_root"
function bake.cmd.list_up(){
  local path="${1:-_root}"
  local up="$path"
  while [[ "$up" != "" ]]; do
    printf '%s\n' "$up"
    up=$(bake.path.dirname "$up" ".")
  done
  if [[ "$path" != "_root" ]]; then printf "_root\n"; fi
}
# Usage: bake.cmd.list_down <cmd>
# reverse of bake.cmd.list_up
function bake.cmd.list_down(){ bake.cmd.list_up "$1" | tail -r; }
# Usage: bake.str.cutLeft <str> <left>
# bake.path.dirname a/b/c  a/b    => c
bake.str.cutLeft(){ printf "${1#$2}"; }

# Usage: bake.opt.match <cmd> <arg>
# match a <arg> is a option return optionDataPath else return ""
# Sample: bake.opt.match "build" "--dir" someDir
#      => "build.opts.dir"
function bake.opt.match()(
  local cmd=$1 arg=$2
  for optPath in $(bake.opt.list "$cmd") ; do
    local opt;  opt=$(bake.path.basename "$optPath")
    local abbr; abbr=${_data["$optPath/abbr"]}
#    echo "optPath: $optPath opt:$opt abbr:$abbr" >&2
    if [[ "--$opt" == "$arg" || ("$abbr" != "" && "-$abbr" == "$arg") ]] ; then
     printf '%s' "$optPath"  ;
     return 0
    fi
  done
  printf ''
)
# Usage: bake.opt.list <cmd>
# return optionDataPath list
function bake.opt.list()(
  local cmd=$1
  local traverseUpCmd
  for traverseUpCmd in $(bake.cmd.list_up "$cmd" "." ) ; do
    local opt;
    for opt in $(bake.data.children "$traverseUpCmd/opts"); do
      printf '%s\n' "$traverseUpCmd/opts/$opt"  ;
    done
  done
)

# because this func is meta function, so can not use option to add self
_data[bake.opt.add/opts/cmd/name]=cmd
_data[bake.opt.add/opts/cmd/type]=string

_data[bake.opt.add/opts/name/name]=name
_data[bake.opt.add/opts/name/type]=string
_data[bake.opt.add/opts/name/required]=true

_data[bake.opt.add/opts/type/name]=type
_data[bake.opt.add/opts/type/type]=string

_data[bake.opt.add/opts/abbr/name]=abbr
_data[bake.opt.add/opts/abbr/type]=string

# avoid use 'help' as option name,because it is root command option
_data[bake.opt.add/opts/optHelp/name]=optHelp
_data[bake.opt.add/opts/optHelp/type]=string
bake.opt.add(){
  # 模版代码，放到每个需要使用option的函数中，然后就可以使用option了
  eval "$(bake.opt.parse "${FUNCNAME[0]}" "$@")"
  if [[ "$name" == "" ]] ;then
    echo "error: option [--name] required " >&2 && return 1 ;
  fi
  if [[ "$type" == "" ]] ;then
    echo "error: option [--type] required " >&2  && return 1 ;
  fi
  if [[ "$type" != "bool" && "$type" != "string" && "$type" != "list"  ]] ;then
    echo "error: option [--type] must in [bool|string|list] " >&2  && return 1 ;
  fi
  local optPath="$cmd/opts/$name"
  _data[$optPath/name]="$name"
  _data[$optPath/cmd]="$cmd"
  _data[$optPath/type]="$type"
  _data[$optPath/abbr]="$abbr"
  _data[$optPath/optHelp]="$optHelp"
}

# Usage: bake.opt.parse <cmd:default _root> [arg1] [arg2] ...
function bake.opt.parse() {
    local cmd; cmd="${1:_root}"
    shift
    local optCount; optCount=0
    local result;
    # parse opts
    while (( $# > 0 )); do
      local optPath; optPath=$(bake.opt.match "$cmd" "$1")
      local opt;     opt=$(bake.path.basename "$optPath")
      # if arg not a opt , parsing complete;
      if [[ "$opt" == "" ]] ; then break;  fi
      # remove the prefix：build.@fields.opts.base_uri => base_uri
      local optType; optType=${_data["$optPath/type"]}

      case $optType in
        bool)   _data[$cmd/opts/$opt/value]=true;
                optCount=$((optCount+1)) ;
                result+="local $opt=true;\n"
                shift;;
        string) [[ "$2" == "" ]] && echo "error: opt need a value: --$opt <value> " >&2 && return 1 ;
                local optValue; optValue=$(printf '%q' "$2");
                _data[$optPath/value]="$optValue";
                optCount=$((optCount+1))
                result+="local $opt=$optValue;\n"
                shift 2 ;;
        list)   [[ "$2" == "" ]] && echo "error: option $arg need a value arg: $arg <value> " >&2 && return 1 ;
                local optValue; optValue="$2";
                local length; length=${_cmdTree[$optPath/value]};
                if [[  "$length" == "" ]] ;then
                  length=1
                  result+="local $opt;\n"
                else
                  length=$((length+1))
                fi
                local index ; index=$((length-1))
                _cmdTree[$optPath/value]="$length";
                _cmdTree[$optPath/value/$index]="$optValue";
                arr+=("$value")
                result+="${option}+=($(printf '%q',"$optValue"));\n"
#                result+="${option}[$index]=$(printf '%q',"$optValue");\n"
                shift 2 ;;
        *) echo "parse error: not support $cmd.opts.$opt.type: <$optType> " >&2 ; return 1 ;;
      esac
    done
    result+="local optCount=$optCount;\n"
    echo -e "$result" # -e show raw string
}

function bake.help()(
  cmd="$1"
  echo bake.help $cmd
)

# _root is special cmd, it is root of all cmd
bake.opt.add --cmd _root --name "help"    --abbr h --type bool --optHelp "print help, show all commands"
bake.opt.add --cmd _root --name "verbose" --abbr v --type bool --optHelp "verbose, show more info, more hidden commands"

function bake.main() {
    bake.cmd.register
    # parse cmd :
    #   ./bake pub get -v -b
    #     -> { cmd:"pub.get", args:"-v -b" }
    #   ./bake -h
    #     -> { cmd:"", args:"-h" }
    local cmd nextCmd  arg;
    for arg in "$@"; do
      nextCmd="$( [[ "$cmd" == "" ]] && echo "$arg" || echo "$cmd.$arg" )"
      if  [[ "${_cmdTree[$nextCmd]}" == "" ]] ; then  break; fi
      cmd="$nextCmd" ;
      shift ;
    done

    if [[ "$cmd" == "" ]] ; then cmd="_root" ; fi

    eval "$(bake.opt.parse "$cmd" "$@")"

    if [[ "$help" == "true" ]] ; then bake.help "$cmd" ; return 0;  fi

#    # parse opts
    if ! declare -f "$cmd" >/dev/null 2>&1; then
      if [[ "${_cmdTree[$cmd]}" == "PARENT_CMD_NOT_FUNC" ]] ; then bake.help "$cmd" ; return 0; fi
      _error "Error: 404 ,cmd '${cmd}' not define, please define cmd function '${cmd}()'"
      return 1
    fi

    # run cmd chain from _root:
    # ./bake2 pub get   => run _root() -> pub() -> pub.get()
    for upCmd in $(bake.cmd.list_down "$cmd"  ); do
      if  [[ "${_cmdTree[$upCmd]}" == "PARENT_CMD_NOT_FUNC" ]]; then continue ; fi
      $upCmd "$@"
    done
}

##########################################
# app script
# 应用项目补充的公共脚本，不在bake维护范围
##########################################
# print first, then _run
_run() {
  local project; project=$(basename "$PWD")
  [[ "$PWD" == "$BAKE_DIR" ]] && project="_root"
  _log "【${project}】▶︎${FUNCNAME[1]} ▶︎ $*"
  "$@"
  return $?
}

_error(){
  echo -e "ERROR -【▶︎${FUNCNAME[1]}】-︎ $*" >&2
}
_log(){
  echo -e "INFO  -【▶︎${FUNCNAME[1]}】-︎ $*" >&2
}

##########################################
# app cmd script
# 应用的命令脚本
##########################################

pub.get(){
  # 模版代码，放到每个需要使用option的函数中，然后就可以使用option了
  bake.opt.parse "${FUNCNAME[0]}" "$@"
  echo "pub.get [$@]"
}

####################################################
# app entry script & _root cmd
# _root cmd is no function ,all it is this file
####################################################
# cmd settings use bash associative array
_rootHelp="$(cat <<- EOF
____ _    _  _ ___ ___ ____ ____    _  _ ____ ___ ____
|___ |    |  |  |   |  |___ |__/ __ |\ | |  |  |  |___
|    |___ |__|  |   |  |___ |  \    | \| |__|  |  |___
Usage:
./${BAKE_FILE} [cmd] [opts] [args...]

  ./${BAKE_FILE}       # 列子命令看帮助，
  ./${BAKE_FILE} build # 子命令
  ./${BAKE_FILE} run   # 子命令
EOF
)"

# lib_mode use for other script import
if [[ "$1" == "--lib_mode"  ]]; then
  echo "lib_mode import: $BAKE_PATH"
else
  bake.main "$@"
fi
