// /// Generated by gen_maters.dart, please don't edit!

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/src/physics/clamped_simulation.dart' as _i1;
import 'package:note/mate.dart' as _i2;
import 'package:flutter/src/physics/simulation.dart' as _i3;

/// class ClampedSimulation extends Simulation
class ClampedSimulation$Mate extends _i1.ClampedSimulation with _i2.Mate {
  /// ClampedSimulation ClampedSimulation(Simulation simulation, {double xMin = double.negativeInfinity, double xMax = double.infinity, double dxMin = double.negativeInfinity, double dxMax = double.infinity})
  ClampedSimulation$Mate(
    /// requiredParameters: Simulation simulation
    _i3.Simulation simulation, {
    /// optionalParameters: {double xMin = double.negativeInfinity} , default:processed=PrefixedIdentifierImpl
    double xMin = double.negativeInfinity,

    /// optionalParameters: {double xMax = double.infinity} , default:processed=PrefixedIdentifierImpl
    double xMax = double.infinity,

    /// optionalParameters: {double dxMin = double.negativeInfinity} , default:processed=PrefixedIdentifierImpl
    double dxMin = double.negativeInfinity,

    /// optionalParameters: {double dxMax = double.infinity} , default:processed=PrefixedIdentifierImpl
    double dxMax = double.infinity,
  }) : super(
          simulation,
          xMin: xMin,
          xMax: xMax,
          dxMin: dxMin,
          dxMax: dxMax,
        ) {
    mateBuilderName = 'ClampedSimulation';
    matePackageUrl = 'package:flutter/physics.dart';
    mateBuilder = (p) => ClampedSimulation$Mate(
          p.get('simulation').value,
          xMin: p.get('xMin').build(),
          xMax: p.get('xMax').build(),
          dxMin: p.get('dxMin').build(),
          dxMax: p.get('dxMax').build(),
        );
    mateUse(
      'simulation',
      simulation,
      isNamed: false,
    );
    mateUse(
      'xMin',
      xMin,
      isNamed: true,
      defaultValue: double.negativeInfinity,
    );
    mateUse(
      'xMax',
      xMax,
      isNamed: true,
      defaultValue: double.infinity,
    );
    mateUse(
      'dxMin',
      dxMin,
      isNamed: true,
      defaultValue: double.negativeInfinity,
    );
    mateUse(
      'dxMax',
      dxMax,
      isNamed: true,
      defaultValue: double.infinity,
    );
  }
}
