// /// Generated by mate_flutter, please don't edit! Created time: 2023-03-11 13:17:26.410937

import 'package:flutter/src/widgets/image_icon.dart';
import 'package:flutter/src/painting/image_provider.dart';
import 'dart:core';
import 'package:flutter/src/foundation/key.dart';
import 'dart:ui';

/// class ImageIcon extends StatelessWidget
class ImageIcon$Mate extends ImageIcon {
  /// ImageIcon ImageIcon(ImageProvider<Object>? image, {Key? key, double? size, Color? color, String? semanticLabel})
  ImageIcon$Mate(
    /// param: ImageProvider<Object>? image
    ImageProvider<Object>? image, {
    /// param: {Key? key}
    Key? key,

    /// param: {double? size}
    double? size,

    /// param: {Color? color}
    Color? color,

    /// param: {String? semanticLabel}
    String? semanticLabel,
  }) : super(
          image,
          key: key,
          size: size,
          color: color,
          semanticLabel: semanticLabel,
        ) {}
}
