// /// Generated by mate_flutter, please don't edit! Created time: 2023-03-11 13:17:26.494389

import 'package:flutter/src/widgets/pages.dart';
import 'package:flutter/src/widgets/navigator.dart';
import 'dart:core';
import 'package:flutter/src/widgets/routes.dart';
import 'dart:ui';

/// abstract class PageRoute<T> extends ModalRoute<T>
abstract class PageRoute$Mate<T> extends PageRoute<T> {
  /// PageRoute<T> PageRoute({RouteSettings? settings, bool fullscreenDialog = false, bool allowSnapshotting = true})
  PageRoute$Mate({
    /// param: {RouteSettings? settings}
    RouteSettings? settings,

    /// param: {bool fullscreenDialog = false}
    required bool fullscreenDialog,

    /// param: {bool allowSnapshotting = true}
    required bool allowSnapshotting,
  }) : super(
          settings: settings,
          fullscreenDialog: fullscreenDialog,
          allowSnapshotting: allowSnapshotting,
        ) {}
}

/// class PageRouteBuilder<T> extends PageRoute<T>
class PageRouteBuilder$Mate<T> extends PageRouteBuilder<T> {
  /// PageRouteBuilder<T> PageRouteBuilder({RouteSettings? settings, required Widget Function(BuildContext, Animation<double>, Animation<double>) pageBuilder, Widget Function(BuildContext, Animation<double>, Animation<double>, Widget) transitionsBuilder = _defaultTransitionsBuilder, Duration transitionDuration = const Duration(milliseconds: 300), Duration reverseTransitionDuration = const Duration(milliseconds: 300), bool opaque = true, bool barrierDismissible = false, Color? barrierColor, String? barrierLabel, bool maintainState = true, bool fullscreenDialog = false, bool allowSnapshotting = true})
  PageRouteBuilder$Mate({
    /// param: {RouteSettings? settings}
    RouteSettings? settings,

    /// param: {required Widget Function(BuildContext, Animation<double>, Animation<double>) pageBuilder}
    required RoutePageBuilder pageBuilder,

    /// param: {Widget Function(BuildContext, Animation<double>, Animation<double>, Widget) transitionsBuilder = _defaultTransitionsBuilder}
    required RouteTransitionsBuilder transitionsBuilder,

    /// param: {Duration transitionDuration = const Duration(milliseconds: 300)}
    required Duration transitionDuration,

    /// param: {Duration reverseTransitionDuration = const Duration(milliseconds: 300)}
    required Duration reverseTransitionDuration,

    /// param: {bool opaque = true}
    required bool opaque,

    /// param: {bool barrierDismissible = false}
    required bool barrierDismissible,

    /// param: {Color? barrierColor}
    Color? barrierColor,

    /// param: {String? barrierLabel}
    String? barrierLabel,

    /// param: {bool maintainState = true}
    required bool maintainState,

    /// param: {bool fullscreenDialog = false}
    required bool fullscreenDialog,

    /// param: {bool allowSnapshotting = true}
    required bool allowSnapshotting,
  }) : super(
          settings: settings,
          pageBuilder: pageBuilder,
          transitionsBuilder: transitionsBuilder,
          transitionDuration: transitionDuration,
          reverseTransitionDuration: reverseTransitionDuration,
          opaque: opaque,
          barrierDismissible: barrierDismissible,
          barrierColor: barrierColor,
          barrierLabel: barrierLabel,
          maintainState: maintainState,
          fullscreenDialog: fullscreenDialog,
          allowSnapshotting: allowSnapshotting,
        ) {}
}
