// /// Generated by mate_flutter, please don't edit!

import 'package:flutter/src/widgets/scroll_simulation.dart';
import 'dart:core';
import 'package:flutter/src/physics/spring_simulation.dart';
import 'package:flutter/src/physics/tolerance.dart';
import 'package:note/mate.dart';

/// class BouncingScrollSimulation extends Simulation
class BouncingScrollSimulation$Mate extends BouncingScrollSimulation with Mate<BouncingScrollSimulation$Mate> {
  /// BouncingScrollSimulation BouncingScrollSimulation({required double position, required double velocity, required double leadingExtent, required double trailingExtent, required SpringDescription spring, double constantDeceleration = 0, Tolerance tolerance = Tolerance.defaultTolerance})
  BouncingScrollSimulation$Mate({
    /// param: {required double position}
    required double position,

    /// param: {required double velocity}
    required double velocity,

    /// param: {required double leadingExtent}
    required double leadingExtent,

    /// param: {required double trailingExtent}
    required double trailingExtent,

    /// param: {required SpringDescription spring}
    required SpringDescription spring,

    /// param: {double constantDeceleration = 0}
    required double constantDeceleration,

    /// param: {Tolerance tolerance = Tolerance.defaultTolerance}
    required Tolerance tolerance,
  }) : super(
          position: position,
          velocity: velocity,
          leadingExtent: leadingExtent,
          trailingExtent: trailingExtent,
          spring: spring,
          constantDeceleration: constantDeceleration,
          tolerance: tolerance,
        ) {
    mateParams = Params(
      init: this,
      builder: (p) => BouncingScrollSimulation$Mate(
        position: p.getValue('position'),
        velocity: p.getValue('velocity'),
        leadingExtent: p.getValue('leadingExtent'),
        trailingExtent: p.getValue('trailingExtent'),
        spring: p.getValue('spring'),
        constantDeceleration: p.getValue('constantDeceleration'),
        tolerance: p.getValue('tolerance'),
      ),
    );
    mateParams.set(name: 'position', init: position);
    mateParams.set(name: 'velocity', init: velocity);
    mateParams.set(name: 'leadingExtent', init: leadingExtent);
    mateParams.set(name: 'trailingExtent', init: trailingExtent);
    mateParams.set(name: 'spring', init: spring);
    mateParams.set(name: 'constantDeceleration', init: constantDeceleration);
    mateParams.set(name: 'tolerance', init: tolerance);
  }
}

/// class ClampingScrollSimulation extends Simulation
class ClampingScrollSimulation$Mate extends ClampingScrollSimulation with Mate<ClampingScrollSimulation$Mate> {
  /// ClampingScrollSimulation ClampingScrollSimulation({required double position, required double velocity, double friction = 0.015, Tolerance tolerance = Tolerance.defaultTolerance})
  ClampingScrollSimulation$Mate({
    /// param: {required double position}
    required double position,

    /// param: {required double velocity}
    required double velocity,

    /// param: {double friction = 0.015}
    required double friction,

    /// param: {Tolerance tolerance = Tolerance.defaultTolerance}
    required Tolerance tolerance,
  }) : super(
          position: position,
          velocity: velocity,
          friction: friction,
          tolerance: tolerance,
        ) {
    mateParams = Params(
      init: this,
      builder: (p) => ClampingScrollSimulation$Mate(
        position: p.getValue('position'),
        velocity: p.getValue('velocity'),
        friction: p.getValue('friction'),
        tolerance: p.getValue('tolerance'),
      ),
    );
    mateParams.set(name: 'position', init: position);
    mateParams.set(name: 'velocity', init: velocity);
    mateParams.set(name: 'friction', init: friction);
    mateParams.set(name: 'tolerance', init: tolerance);
  }
}
