// /// Generated by mate_flutter, please don't edit!

import 'package:flutter/src/widgets/value_listenable_builder.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/foundation/change_notifier.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:note/mate.dart';

/// class ValueListenableBuilder<T> extends StatefulWidget
class ValueListenableBuilder$Mate<T> extends ValueListenableBuilder<T> with WidgetMate<ValueListenableBuilder$Mate> {
  /// ValueListenableBuilder<T> ValueListenableBuilder({Key? key, required ValueListenable<T> valueListenable, required Widget Function(BuildContext, T, Widget?) builder, Widget? child})
  ValueListenableBuilder$Mate({
    /// param: {Key? key}
    Key? key,

    /// param: {required ValueListenable<T> valueListenable}
    required ValueListenable<T> valueListenable,

    /// param: {required Widget Function(BuildContext, T, Widget?) builder}
    required ValueWidgetBuilder<T> builder,

    /// param: {Widget? child}
    Widget? child,
  }) : super(
          key: key,
          valueListenable: valueListenable,
          builder: builder,
          child: child,
        ) {
    mateParams = Params(
      init: this,
      builder: (p) => ValueListenableBuilder$Mate(
        key: p.getValue('key'),
        valueListenable: p.getValue('valueListenable'),
        builder: p.getValue('builder'),
        child: p.getValue('child'),
      ),
    );
    mateParams.set(name: 'key', init: key);
    mateParams.set(name: 'valueListenable', init: valueListenable);
    mateParams.set(name: 'builder', init: builder);
    mateParams.set(name: 'child', init: child);
  }
}
