// /// Generated by mate_flutter, please don't edit!

import 'package:flutter/src/material/tooltip_visibility.dart';
import 'package:flutter/src/foundation/key.dart';
import 'dart:core';
import 'package:flutter/src/widgets/framework.dart';
import 'package:note/mate.dart';

/// class TooltipVisibility extends StatelessWidget
class TooltipVisibility$Mate extends TooltipVisibility with WidgetMate<TooltipVisibility$Mate> {
  /// TooltipVisibility TooltipVisibility({Key? key, required bool visible, required Widget child})
  TooltipVisibility$Mate({
    /// param: {Key? key}
    Key? key,

    /// param: {required bool visible}
    required bool visible,

    /// param: {required Widget child}
    required Widget child,
  }) : super(
          key: key,
          visible: visible,
          child: child,
        ) {
    mateParams = Params(
      init: this,
      builder: (p) => TooltipVisibility$Mate(
        key: p.getValue('key'),
        visible: p.getValue('visible'),
        child: p.getValue('child'),
      ),
    );
    mateParams.set(name: 'key', init: key);
    mateParams.set(name: 'visible', init: visible);
    mateParams.set(name: 'child', init: child);
  }
}
