// /// Generated by gen_maters.dart, please don't edit!

noteInfo() => (
      cells: [
        /// ()
        (
          cellType: 'header',
          offset: 0,
          end: 113,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        ),

        /// (print.markdown(r'''  # 布局  ## )
        (
          cellType: 'body',
          offset: 113,
          end: 811,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        ),

        /// ()
        (
          cellType: 'tail',
          offset: 811,
          end: 813,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        )
      ],
      encodedCode:
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvd2lkZ2V0cy5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOm5vdGUvbm90ZS5kYXJ0JzsKCmJ1aWxkKEJ1aWxkQ29udGV4dCBjb250ZXh0LCBQZW4gcHJpbnQpIHsKICBwcmludC5tYXJrZG93bihyJycnCgojIOW4g+WxgAoKIyMg57qm5p2fCgpMYXlvdXRCdWlsZGVyCgojIyDlvLnmgKfluIPlsYAKCi0gRmxleCA8aHR0cHM6Ly9hcGkuZmx1dHRlci1pby5jbi9mbHV0dGVyL3dpZGdldHMvRmxleC1jbGFzcy5odG1sPgogIC0gUm93CiAgLSBDb2x1bW4KCiMjIOW4g+WxgOaVhemanOWkhOeQhu+8mkludHJpbnNpY0hlaWdodApSb3coCiAgICAgICAgbWFpbkF4aXNTaXplOiBNYWluQXhpc1NpemUubWluLAogICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICBJbnRyaW5zaWNIZWlnaHQoCiAgICAgICAgICAgIGNoaWxkOiBuYXZpZ2F0aW9uUmFpbCwKICAgICAgICAgICkKICAgICAgICBdLAogICAgICApCgoKIyMg5biD5bGA6Zeu6aKYCgojIyMgRmxleCAmIEZsZXhpYmxlCgogICAgICAvLyB0aXRsZSDooqtGbGV4aWJsZeWMheijueWQju+8jOaWh+acrOWkqumVv+S8muiHquWKqOaNouihjAogICAgICAvLyDkvYbmmK9GbGV4aWJsZeimgeS4iumdouWll+S4gOS4qkZsZXjnmoTlrZDnsbsKICAgICAgdmFyIGxpbmtfb2xkID0gVGV4dEJ1dHRvbigKICAgICAgICBjaGlsZDogUm93KAogICAgICAgICAgY3Jvc3NBeGlzQWxpZ25tZW50OiBDcm9zc0F4aXNBbGlnbm1lbnQuY2VudGVyLAogICAgICAgICAgY2hpbGRyZW46IFsKICAgICAgICAgICAgVGV4dChpY29uRXh0ZW5kKSwKICAgICAgICAgICAgRmxleGlibGUoY2hpbGQ6IFRleHQoIvCfl5MgJHtub2RlLnNob3J0VGl0bGV9IikpLAogICAgICAgICAgXSwKICAgICAgICApLAogICAgICApOwogICcnJyk7Cn0K"
    );
