// /// Generated by mat_flutter, please don't edit! Created time: 2023-03-09 00:16:00.643907

library;

import 'dart:core';
export 'package:flutter/foundation.dart' show DiagnosticPropertiesBuilder;

/// abstract class KeyboardKey with Diagnosticable
abstract class KeyboardKeyMate {
  /// KeyboardKey KeyboardKey()
  KeyboardKeyMate() {}
}

/// class LogicalKeyboardKey extends KeyboardKey
class LogicalKeyboardKeyMate {
  /// LogicalKeyboardKey LogicalKeyboardKey(int keyId)
  LogicalKeyboardKeyMate(
// param: int keyId
      int keyId) {}
}

/// class PhysicalKeyboardKey extends KeyboardKey
class PhysicalKeyboardKeyMate {
  /// PhysicalKeyboardKey PhysicalKeyboardKey(int usbHidUsage)
  PhysicalKeyboardKeyMate(
// param: int usbHidUsage
      int usbHidUsage) {}
}
