// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/painting/gradient.dart';
import 'package:note/mate.dart';
import 'dart:core';
import 'package:flutter/src/painting/alignment.dart';
import 'dart:ui';

/// class GradientRotation extends GradientTransform
class GradientRotation$Mate extends GradientRotation with Mate {
  /// GradientRotation GradientRotation(double radians)
  GradientRotation$Mate(

      /// requiredParameters: double radians
      double radians)
      : super(radians) {
    mateCreateName = 'GradientRotation';
    matePackageUrl = 'package:flutter/material.dart';
    mateBuilder = (p) => GradientRotation$Mate(p.get('radians').value);
    mateUse('radians', radians);
  }
}

/// class LinearGradient extends Gradient
class LinearGradient$Mate extends LinearGradient with Mate {
  /// LinearGradient LinearGradient({AlignmentGeometry begin = Alignment.centerLeft, AlignmentGeometry end = Alignment.centerRight, required List<Color> colors, List<double>? stops, TileMode tileMode = TileMode.clamp, GradientTransform? transform})
  LinearGradient$Mate({
    /// optionalParameters: {AlignmentGeometry begin = Alignment.centerLeft} , defaultValue:unprocessed
    required AlignmentGeometry begin,

    /// optionalParameters: {AlignmentGeometry end = Alignment.centerRight} , defaultValue:unprocessed
    required AlignmentGeometry end,

    /// optionalParameters: {required List<Color> colors} , defaultValue:none
    required List<Color> colors,

    /// optionalParameters: {List<double>? stops} , defaultValue:none
    List<double>? stops,

    /// optionalParameters: {TileMode tileMode = TileMode.clamp} , defaultValue:unprocessed
    required TileMode tileMode,

    /// optionalParameters: {GradientTransform? transform} , defaultValue:none
    GradientTransform? transform,
  }) : super(
          begin: begin,
          end: end,
          colors: colors,
          stops: stops,
          tileMode: tileMode,
          transform: transform,
        ) {
    mateCreateName = 'LinearGradient';
    matePackageUrl = 'package:flutter/material.dart';
    mateBuilder = (p) => LinearGradient$Mate(
          begin: p.get('begin').build(),
          end: p.get('end').build(),
          colors: p.get('colors').build(),
          stops: p.get('stops').build(),
          tileMode: p.get('tileMode').build(),
          transform: p.get('transform').build(),
        );
    mateUse('begin', begin);
    mateUse('end', end);
    mateUse('colors', colors);
    mateUse('stops', stops);
    mateUse('tileMode', tileMode);
    mateUse('transform', transform);
  }
}

/// class RadialGradient extends Gradient
class RadialGradient$Mate extends RadialGradient with Mate {
  /// RadialGradient RadialGradient({AlignmentGeometry center = Alignment.center, double radius = 0.5, required List<Color> colors, List<double>? stops, TileMode tileMode = TileMode.clamp, AlignmentGeometry? focal, double focalRadius = 0.0, GradientTransform? transform})
  RadialGradient$Mate({
    /// optionalParameters: {AlignmentGeometry center = Alignment.center} , defaultValue:unprocessed
    required AlignmentGeometry center,

    /// optionalParameters: {double radius = 0.5} , defaultValue:Literal
    double radius = 0.5,

    /// optionalParameters: {required List<Color> colors} , defaultValue:none
    required List<Color> colors,

    /// optionalParameters: {List<double>? stops} , defaultValue:none
    List<double>? stops,

    /// optionalParameters: {TileMode tileMode = TileMode.clamp} , defaultValue:unprocessed
    required TileMode tileMode,

    /// optionalParameters: {AlignmentGeometry? focal} , defaultValue:none
    AlignmentGeometry? focal,

    /// optionalParameters: {double focalRadius = 0.0} , defaultValue:Literal
    double focalRadius = 0.0,

    /// optionalParameters: {GradientTransform? transform} , defaultValue:none
    GradientTransform? transform,
  }) : super(
          center: center,
          radius: radius,
          colors: colors,
          stops: stops,
          tileMode: tileMode,
          focal: focal,
          focalRadius: focalRadius,
          transform: transform,
        ) {
    mateCreateName = 'RadialGradient';
    matePackageUrl = 'package:flutter/material.dart';
    mateBuilder = (p) => RadialGradient$Mate(
          center: p.get('center').build(),
          radius: p.get('radius').build(),
          colors: p.get('colors').build(),
          stops: p.get('stops').build(),
          tileMode: p.get('tileMode').build(),
          focal: p.get('focal').build(),
          focalRadius: p.get('focalRadius').build(),
          transform: p.get('transform').build(),
        );
    mateUse('center', center);
    mateUse('radius', radius);
    mateUse('colors', colors);
    mateUse('stops', stops);
    mateUse('tileMode', tileMode);
    mateUse('focal', focal);
    mateUse('focalRadius', focalRadius);
    mateUse('transform', transform);
  }
}

/// class SweepGradient extends Gradient
class SweepGradient$Mate extends SweepGradient with Mate {
  /// SweepGradient SweepGradient({AlignmentGeometry center = Alignment.center, double startAngle = 0.0, double endAngle = math.pi * 2, required List<Color> colors, List<double>? stops, TileMode tileMode = TileMode.clamp, GradientTransform? transform})
  SweepGradient$Mate({
    /// optionalParameters: {AlignmentGeometry center = Alignment.center} , defaultValue:unprocessed
    required AlignmentGeometry center,

    /// optionalParameters: {double startAngle = 0.0} , defaultValue:Literal
    double startAngle = 0.0,

    /// optionalParameters: {double endAngle = math.pi * 2} , defaultValue:unprocessed
    required double endAngle,

    /// optionalParameters: {required List<Color> colors} , defaultValue:none
    required List<Color> colors,

    /// optionalParameters: {List<double>? stops} , defaultValue:none
    List<double>? stops,

    /// optionalParameters: {TileMode tileMode = TileMode.clamp} , defaultValue:unprocessed
    required TileMode tileMode,

    /// optionalParameters: {GradientTransform? transform} , defaultValue:none
    GradientTransform? transform,
  }) : super(
          center: center,
          startAngle: startAngle,
          endAngle: endAngle,
          colors: colors,
          stops: stops,
          tileMode: tileMode,
          transform: transform,
        ) {
    mateCreateName = 'SweepGradient';
    matePackageUrl = 'package:flutter/material.dart';
    mateBuilder = (p) => SweepGradient$Mate(
          center: p.get('center').build(),
          startAngle: p.get('startAngle').build(),
          endAngle: p.get('endAngle').build(),
          colors: p.get('colors').build(),
          stops: p.get('stops').build(),
          tileMode: p.get('tileMode').build(),
          transform: p.get('transform').build(),
        );
    mateUse('center', center);
    mateUse('startAngle', startAngle);
    mateUse('endAngle', endAngle);
    mateUse('colors', colors);
    mateUse('stops', stops);
    mateUse('tileMode', tileMode);
    mateUse('transform', transform);
  }
}
