// /// Generated by gen_maters.dart, please don't edit!

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/src/rendering/flex.dart' as _i1;
import 'package:note/mate_core.dart' as _i2;
import 'package:flutter/src/rendering/box.dart' as _i3;
import 'package:flutter/src/painting/basic_types.dart' as _i4;
import 'package:flutter/cupertino.dart' as _i5;
import 'dart:ui' as _i6;

/// class RenderFlex extends RenderBox with ContainerRenderObjectMixin<RenderBox, FlexParentData>, RenderBoxContainerDefaultsMixin<RenderBox, FlexParentData>, DebugOverflowIndicatorMixin
class RenderFlex$Mate extends _i1.RenderFlex with _i2.Mate {
  /// RenderFlex RenderFlex({List<RenderBox>? children, Axis direction = Axis.horizontal, MainAxisSize mainAxisSize = MainAxisSize.max, MainAxisAlignment mainAxisAlignment = MainAxisAlignment.start, CrossAxisAlignment crossAxisAlignment = CrossAxisAlignment.center, TextDirection? textDirection, VerticalDirection verticalDirection = VerticalDirection.down, TextBaseline? textBaseline, Clip clipBehavior = Clip.none})
  RenderFlex$Mate({
    /// optionalParameters: {List<RenderBox>? children} , default:none
    super.children,

    /// optionalParameters: {Axis direction = Axis.horizontal} , default:processed=PrefixedIdentifierImpl
    super.direction,

    /// optionalParameters: {MainAxisSize mainAxisSize = MainAxisSize.max} , default:processed=PrefixedIdentifierImpl
    super.mainAxisSize,

    /// optionalParameters: {MainAxisAlignment mainAxisAlignment = MainAxisAlignment.start} , default:processed=PrefixedIdentifierImpl
    super.mainAxisAlignment,

    /// optionalParameters: {CrossAxisAlignment crossAxisAlignment = CrossAxisAlignment.center} , default:processed=PrefixedIdentifierImpl
    super.crossAxisAlignment,

    /// optionalParameters: {TextDirection? textDirection} , default:none
    super.textDirection,

    /// optionalParameters: {VerticalDirection verticalDirection = VerticalDirection.down} , default:processed=PrefixedIdentifierImpl
    super.verticalDirection,

    /// optionalParameters: {TextBaseline? textBaseline} , default:none
    super.textBaseline,

    /// optionalParameters: {Clip clipBehavior = Clip.none} , default:processed=PrefixedIdentifierImpl
    super.clipBehavior,
  })  : mateParams = {
          'children': _i2.BuilderArg<List<_i3.RenderBox>?>(
            name: 'children',
            init: children,
            isNamed: true,
          ),
          'direction': _i2.BuilderArg<_i4.Axis>(
            name: 'direction',
            init: direction,
            isNamed: true,
            defaultValue: _i5.Axis.horizontal,
          ),
          'mainAxisSize': _i2.BuilderArg<_i1.MainAxisSize>(
            name: 'mainAxisSize',
            init: mainAxisSize,
            isNamed: true,
            defaultValue: _i5.MainAxisSize.max,
          ),
          'mainAxisAlignment': _i2.BuilderArg<_i1.MainAxisAlignment>(
            name: 'mainAxisAlignment',
            init: mainAxisAlignment,
            isNamed: true,
            defaultValue: _i5.MainAxisAlignment.start,
          ),
          'crossAxisAlignment': _i2.BuilderArg<_i1.CrossAxisAlignment>(
            name: 'crossAxisAlignment',
            init: crossAxisAlignment,
            isNamed: true,
            defaultValue: _i5.CrossAxisAlignment.center,
          ),
          'textDirection': _i2.BuilderArg<_i6.TextDirection?>(
            name: 'textDirection',
            init: textDirection,
            isNamed: true,
          ),
          'verticalDirection': _i2.BuilderArg<_i4.VerticalDirection>(
            name: 'verticalDirection',
            init: verticalDirection,
            isNamed: true,
            defaultValue: _i5.VerticalDirection.down,
          ),
          'textBaseline': _i2.BuilderArg<_i6.TextBaseline?>(
            name: 'textBaseline',
            init: textBaseline,
            isNamed: true,
          ),
          'clipBehavior': _i2.BuilderArg<_i6.Clip>(
            name: 'clipBehavior',
            init: clipBehavior,
            isNamed: true,
            defaultValue: _i6.Clip.none,
          ),
        },
        super() {
    mateBuilderName = 'RenderFlex';
    matePackageUrl = 'package:flutter/rendering.dart';
    mateBuilder = (p) => RenderFlex$Mate(
          children: p.get('children').build(),
          direction: p.get('direction').build(),
          mainAxisSize: p.get('mainAxisSize').build(),
          mainAxisAlignment: p.get('mainAxisAlignment').build(),
          crossAxisAlignment: p.get('crossAxisAlignment').build(),
          textDirection: p.get('textDirection').build(),
          verticalDirection: p.get('verticalDirection').build(),
          textBaseline: p.get('textBaseline').build(),
          clipBehavior: p.get('clipBehavior').build(),
        );
  }

  @override
  final Map<String, _i2.BuilderArg> mateParams;
}
