// /// Generated by mate_flutter, please don't edit! Created time: 2023-03-11 00:36:14.058469

import 'package:flutter/src/foundation/key.dart';

/// class ValueKey<T> extends LocalKey
class ValueKeyMate<T> extends ValueKey<T> {
  /// ValueKey<T> ValueKey(T value)
  ValueKeyMate(

      /// param: T value
      T value)
      : super(value) {}
}
