// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/foundation/assertions.dart';
import 'dart:core';
import 'package:note/mate.dart';
import 'package:flutter/src/foundation/diagnostics.dart';
import 'package:flutter/src/foundation/basic_types.dart';

/// class PartialStackFrame
class PartialStackFrame$Mate extends PartialStackFrame with Mate<PartialStackFrame$Mate> {
  /// PartialStackFrame PartialStackFrame({required Pattern package, required String className, required String method})
  PartialStackFrame$Mate({
    /// optionalParameters: {required Pattern package} , hasDefaultValue:false, defaultValueCode:null
    required Pattern package,

    /// optionalParameters: {required String className} , hasDefaultValue:false, defaultValueCode:null
    required String className,

    /// optionalParameters: {required String method} , hasDefaultValue:false, defaultValueCode:null
    required String method,
  }) : super(
          package: package,
          className: className,
          method: method,
        ) {
    mateParams = Params(
      init: this,
      builder: (p) => PartialStackFrame$Mate(
        package: p.getValue('package'),
        className: p.getValue('className'),
        method: p.getValue('method'),
      ),
    );
    mateParams.set(name: 'package', init: package);
    mateParams.set(name: 'className', init: className);
    mateParams.set(name: 'method', init: method);
  }
}

/// class RepetitiveStackFrameFilter extends StackFilter
class RepetitiveStackFrameFilter$Mate extends RepetitiveStackFrameFilter with Mate<RepetitiveStackFrameFilter$Mate> {
  /// RepetitiveStackFrameFilter RepetitiveStackFrameFilter({required List<PartialStackFrame> frames, required String replacement})
  RepetitiveStackFrameFilter$Mate({
    /// optionalParameters: {required List<PartialStackFrame> frames} , hasDefaultValue:false, defaultValueCode:null
    required List<PartialStackFrame> frames,

    /// optionalParameters: {required String replacement} , hasDefaultValue:false, defaultValueCode:null
    required String replacement,
  }) : super(
          frames: frames,
          replacement: replacement,
        ) {
    mateParams = Params(
      init: this,
      builder: (p) => RepetitiveStackFrameFilter$Mate(
        frames: p.getValue('frames'),
        replacement: p.getValue('replacement'),
      ),
    );
    mateParams.set(name: 'frames', init: frames);
    mateParams.set(name: 'replacement', init: replacement);
  }
}

/// class ErrorDescription extends _ErrorDiagnostic
class ErrorDescription$Mate extends ErrorDescription with Mate<ErrorDescription$Mate> {
  /// ErrorDescription ErrorDescription(String message)
  ErrorDescription$Mate(

      /// requiredParameters: String message
      String message)
      : super(message) {
    mateParams = Params(
      init: this,
      builder: (p) => ErrorDescription$Mate(p.getValue('message')),
    );
    mateParams.set(name: 'message', init: message);
  }
}

/// class ErrorSummary extends _ErrorDiagnostic
class ErrorSummary$Mate extends ErrorSummary with Mate<ErrorSummary$Mate> {
  /// ErrorSummary ErrorSummary(String message)
  ErrorSummary$Mate(

      /// requiredParameters: String message
      String message)
      : super(message) {
    mateParams = Params(
      init: this,
      builder: (p) => ErrorSummary$Mate(p.getValue('message')),
    );
    mateParams.set(name: 'message', init: message);
  }
}

/// class ErrorHint extends _ErrorDiagnostic
class ErrorHint$Mate extends ErrorHint with Mate<ErrorHint$Mate> {
  /// ErrorHint ErrorHint(String message)
  ErrorHint$Mate(

      /// requiredParameters: String message
      String message)
      : super(message) {
    mateParams = Params(
      init: this,
      builder: (p) => ErrorHint$Mate(p.getValue('message')),
    );
    mateParams.set(name: 'message', init: message);
  }
}

/// class FlutterErrorDetails with Diagnosticable
class FlutterErrorDetails$Mate extends FlutterErrorDetails with Mate<FlutterErrorDetails$Mate> {
  /// FlutterErrorDetails FlutterErrorDetails({required Object exception, StackTrace? stack, String? library = 'Flutter framework', DiagnosticsNode? context, Iterable<String> Function(Iterable<String>)? stackFilter, Iterable<DiagnosticsNode> Function()? informationCollector, bool silent = false})
  FlutterErrorDetails$Mate({
    /// optionalParameters: {required Object exception} , hasDefaultValue:false, defaultValueCode:null
    required Object exception,

    /// optionalParameters: {StackTrace? stack} , hasDefaultValue:false, defaultValueCode:null
    StackTrace? stack,

    /// optionalParameters: {String? library = 'Flutter framework'} , hasDefaultValue:true, defaultValueCode:'Flutter framework'
    String? library,

    /// optionalParameters: {DiagnosticsNode? context} , hasDefaultValue:false, defaultValueCode:null
    DiagnosticsNode? context,

    /// optionalParameters: {Iterable<String> Function(Iterable<String>)? stackFilter} , hasDefaultValue:false, defaultValueCode:null
    IterableFilter<String>? stackFilter,

    /// optionalParameters: {Iterable<DiagnosticsNode> Function()? informationCollector} , hasDefaultValue:false, defaultValueCode:null
    InformationCollector? informationCollector,

    /// optionalParameters: {bool silent = false} , hasDefaultValue:true, defaultValueCode:false
    required bool silent,
  }) : super(
          exception: exception,
          stack: stack,
          library: library,
          context: context,
          stackFilter: stackFilter,
          informationCollector: informationCollector,
          silent: silent,
        ) {
    mateParams = Params(
      init: this,
      builder: (p) => FlutterErrorDetails$Mate(
        exception: p.getValue('exception'),
        stack: p.getValue('stack'),
        library: p.getValue('library'),
        context: p.getValue('context'),
        stackFilter: p.getValue('stackFilter'),
        informationCollector: p.getValue('informationCollector'),
        silent: p.getValue('silent'),
      ),
    );
    mateParams.set(name: 'exception', init: exception);
    mateParams.set(name: 'stack', init: stack);
    mateParams.set(name: 'library', init: library);
    mateParams.set(name: 'context', init: context);
    mateParams.set(name: 'stackFilter', init: stackFilter);
    mateParams.set(name: 'informationCollector', init: informationCollector);
    mateParams.set(name: 'silent', init: silent);
  }
}

/// class FlutterError extends Error with DiagnosticableTreeMixin implements AssertionError
class FlutterError$Mate extends FlutterError with Mate<FlutterError$Mate> {
  /// FlutterError FlutterError.fromParts(List<DiagnosticsNode> diagnostics)
  FlutterError$Mate.fromParts(

      /// requiredParameters: List<DiagnosticsNode> diagnostics
      List<DiagnosticsNode> diagnostics)
      : super.fromParts(diagnostics) {
    mateParams = Params(
      init: this,
      builder: (p) => FlutterError$Mate.fromParts(p.getValue('diagnostics')),
    );
    mateParams.set(name: 'diagnostics', init: diagnostics);
  }
}

/// class DiagnosticsStackTrace extends DiagnosticsBlock
class DiagnosticsStackTrace$Mate extends DiagnosticsStackTrace with Mate<DiagnosticsStackTrace$Mate> {
  /// DiagnosticsStackTrace DiagnosticsStackTrace(String name, StackTrace? stack, {Iterable<String> Function(Iterable<String>)? stackFilter, bool showSeparator = true})
  DiagnosticsStackTrace$Mate(
    /// requiredParameters: String name
    String name,

    /// requiredParameters: StackTrace? stack
    StackTrace? stack, {
    /// optionalParameters: {Iterable<String> Function(Iterable<String>)? stackFilter} , hasDefaultValue:false, defaultValueCode:null
    IterableFilter<String>? stackFilter,

    /// optionalParameters: {bool showSeparator = true} , hasDefaultValue:true, defaultValueCode:true
    required bool showSeparator,
  }) : super(
          name,
          stack,
          stackFilter: stackFilter,
          showSeparator: showSeparator,
        ) {
    mateParams = Params(
      init: this,
      builder: (p) => DiagnosticsStackTrace$Mate(
        p.getValue('name'),
        p.getValue('stack'),
        stackFilter: p.getValue('stackFilter'),
        showSeparator: p.getValue('showSeparator'),
      ),
    );
    mateParams.set(name: 'name', init: name);
    mateParams.set(name: 'stack', init: stack);
    mateParams.set(name: 'stackFilter', init: stackFilter);
    mateParams.set(name: 'showSeparator', init: showSeparator);
  }

  /// DiagnosticsStackTrace DiagnosticsStackTrace.singleFrame(String name, {required String frame, bool showSeparator = true})
  DiagnosticsStackTrace$Mate.singleFrame(
    /// requiredParameters: String name
    String name, {
    /// optionalParameters: {required String frame} , hasDefaultValue:false, defaultValueCode:null
    required String frame,

    /// optionalParameters: {bool showSeparator = true} , hasDefaultValue:true, defaultValueCode:true
    required bool showSeparator,
  }) : super.singleFrame(
          name,
          frame: frame,
          showSeparator: showSeparator,
        ) {
    mateParams = Params(
      init: this,
      builder: (p) => DiagnosticsStackTrace$Mate.singleFrame(
        p.getValue('name'),
        frame: p.getValue('frame'),
        showSeparator: p.getValue('showSeparator'),
      ),
    );
    mateParams.set(name: 'name', init: name);
    mateParams.set(name: 'frame', init: frame);
    mateParams.set(name: 'showSeparator', init: showSeparator);
  }
}
