// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/services/asset_bundle.dart';
import 'dart:core';
import 'package:note/mate.dart';

/// class NetworkAssetBundle extends AssetBundle
class NetworkAssetBundle$Mate extends NetworkAssetBundle with Mate<NetworkAssetBundle$Mate> {
  /// NetworkAssetBundle NetworkAssetBundle(Uri baseUrl)
  NetworkAssetBundle$Mate(

      /// requiredParameters: Uri baseUrl
      Uri baseUrl)
      : super(baseUrl) {
    mateParams = ObjectParam(
      init: this,
      builder: (p) => NetworkAssetBundle$Mate(p.get('baseUrl').value),
    );
    mateParams.put('baseUrl', init: baseUrl);
  }
}
