// /// Generated by mate_flutter, please don't edit! Created time: 2023-03-11 13:17:25.509170

import 'package:flutter/src/services/text_editing.dart';
import 'dart:core';
import 'dart:ui';
export 'dart:ui' show TextAffinity, TextPosition;

/// class TextSelection extends TextRange
class TextSelection$Mate extends TextSelection {
  /// TextSelection TextSelection({required int baseOffset, required int extentOffset, TextAffinity affinity = TextAffinity.downstream, bool isDirectional = false})
  TextSelection$Mate({
    /// param: {required int baseOffset}
    required int baseOffset,

    /// param: {required int extentOffset}
    required int extentOffset,

    /// param: {TextAffinity affinity = TextAffinity.downstream}
    required TextAffinity affinity,

    /// param: {bool isDirectional = false}
    required bool isDirectional,
  }) : super(
          baseOffset: baseOffset,
          extentOffset: extentOffset,
          affinity: affinity,
          isDirectional: isDirectional,
        ) {}

  /// TextSelection TextSelection.collapsed({required int offset, TextAffinity affinity = TextAffinity.downstream})
  TextSelection$Mate.collapsed({
    /// param: {required int offset}
    required int offset,

    /// param: {TextAffinity affinity = TextAffinity.downstream}
    required TextAffinity affinity,
  }) : super.collapsed(
          offset: offset,
          affinity: affinity,
        ) {}

  /// TextSelection TextSelection.fromPosition(TextPosition position)
  TextSelection$Mate.fromPosition(

      /// param: TextPosition position
      TextPosition position)
      : super.fromPosition(position) {}
}
