// /// Generated by gen_maters.dart, please don't edit!

noteInfo() => (
      cells: [
        /// ()
        (
          cellType: 'header',
          offset: 0,
          end: 197,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        ),

        /// ()
        (
          cellType: 'body',
          offset: 197,
          end: 200,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        ),

        /// (print.markdown(r''' # 异步  很好的异)
        (
          cellType: 'body',
          offset: 278,
          end: 548,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        ),

        /// ({Future<String> bomb() async {)
        (
          cellType: 'body',
          offset: 626,
          end: 1359,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        ),

        /// (print.markdown(r''' ## Isalted)
        (
          cellType: 'body',
          offset: 1437,
          end: 1918,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        ),

        /// ({send123(sendPort) async {for )
        (
          cellType: 'body',
          offset: 1996,
          end: 2645,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        ),

        /// ()
        (
          cellType: 'tail',
          offset: 2645,
          end: 2647,
          specialNodes: <({
            String nodeType,
            int end,
            int offset,
          })>[],
        )
      ],
    );
