// /// Generated by gen_maters.dart, please don't edit! 

import 'package:flutter/src/widgets/animated_switcher.dart';import 'package:flutter/src/foundation/key.dart';import 'package:flutter/src/widgets/framework.dart';import 'dart:core';import 'package:flutter/src/animation/curves.dart';import 'package:note/mate.dart' show Mate;/// class AnimatedSwitcher extends StatefulWidget
class AnimatedSwitcher$Mate extends AnimatedSwitcher with Mate {/// AnimatedSwitcher AnimatedSwitcher({Key? key, Widget? child, required Duration duration, Duration? reverseDuration, Curve switchInCurve = Curves.linear, Curve switchOutCurve = Curves.linear, Widget Function(Widget, Animation<double>) transitionBuilder = AnimatedSwitcher.defaultTransitionBuilder, Widget Function(Widget?, List<Widget>) layoutBuilder = AnimatedSwitcher.defaultLayoutBuilder})
AnimatedSwitcher$Mate({/// optionalParameters: {Key? key} , hasDefaultValue:false, defaultValueCode:null
Key? key, /// optionalParameters: {Widget? child} , hasDefaultValue:false, defaultValueCode:null
Widget? child, /// optionalParameters: {required Duration duration} , hasDefaultValue:false, defaultValueCode:null
required Duration duration, /// optionalParameters: {Duration? reverseDuration} , hasDefaultValue:false, defaultValueCode:null
Duration? reverseDuration, /// optionalParameters: {Curve switchInCurve = Curves.linear} , hasDefaultValue:true, defaultValueCode:Curves.linear
required Curve switchInCurve, /// optionalParameters: {Curve switchOutCurve = Curves.linear} , hasDefaultValue:true, defaultValueCode:Curves.linear
required Curve switchOutCurve, /// optionalParameters: {Widget Function(Widget, Animation<double>) transitionBuilder = AnimatedSwitcher.defaultTransitionBuilder} , hasDefaultValue:true, defaultValueCode:AnimatedSwitcher.defaultTransitionBuilder
required AnimatedSwitcherTransitionBuilder transitionBuilder, /// optionalParameters: {Widget Function(Widget?, List<Widget>) layoutBuilder = AnimatedSwitcher.defaultLayoutBuilder} , hasDefaultValue:true, defaultValueCode:AnimatedSwitcher.defaultLayoutBuilder
required AnimatedSwitcherLayoutBuilder layoutBuilder, }) : super(key: key, child: child, duration: duration, reverseDuration: reverseDuration, switchInCurve: switchInCurve, switchOutCurve: switchOutCurve, transitionBuilder: transitionBuilder, layoutBuilder: layoutBuilder, ) { mateBuilder = (p) => AnimatedSwitcher$Mate(key: p.get('key').build(), child: p.get('child').build(), duration: p.get('duration').build(), reverseDuration: p.get('reverseDuration').build(), switchInCurve: p.get('switchInCurve').build(), switchOutCurve: p.get('switchOutCurve').build(), transitionBuilder: p.get('transitionBuilder').build(), layoutBuilder: p.get('layoutBuilder').build(), );
matePut('key', key);
matePut('child', child);
matePut('duration', duration);
matePut('reverseDuration', reverseDuration);
matePut('switchInCurve', switchInCurve);
matePut('switchOutCurve', switchOutCurve);
matePut('transitionBuilder', transitionBuilder);
matePut('layoutBuilder', layoutBuilder); }

 }
