// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/widgets/context_menu_controller.dart';
import 'package:note/mate.dart';
import 'dart:ui';

/// class ContextMenuController
class ContextMenuController$Mate extends ContextMenuController with Mate {
  /// ContextMenuController ContextMenuController({void Function()? onRemove})
  ContextMenuController$Mate(
      {
      /// optionalParameters: {void Function()? onRemove} , hasDefaultValue:false, defaultValueCode:null
      VoidCallback? onRemove})
      : super(onRemove: onRemove) {
    mateBuilder = (p) => ContextMenuController$Mate(onRemove: p.get('onRemove').build());
    matePut('onRemove', onRemove);
  }
}
