// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/widgets/default_text_editing_shortcuts.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:note/mate.dart';

/// class DefaultTextEditingShortcuts extends StatelessWidget
class DefaultTextEditingShortcuts$Mate extends DefaultTextEditingShortcuts with Mate<DefaultTextEditingShortcuts$Mate> {
  /// DefaultTextEditingShortcuts DefaultTextEditingShortcuts({Key? key, required Widget child})
  DefaultTextEditingShortcuts$Mate({
    /// optionalParameters: {Key? key} , hasDefaultValue:false, defaultValueCode:null
    Key? key,

    /// optionalParameters: {required Widget child} , hasDefaultValue:false, defaultValueCode:null
    required Widget child,
  }) : super(
          key: key,
          child: child,
        ) {
    mateParams = ObjectParam(
      init: this,
      builder: (p) => DefaultTextEditingShortcuts$Mate(
        key: p.get('key').build(),
        child: p.get('child').build(),
      ),
    );
    mateParams.put('key', key);
    mateParams.put('child', child);
  }
}
