// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/widgets/focus_traversal.dart';
import 'package:note/mate.dart';
import 'dart:core';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/focus_manager.dart';

/// class NumericFocusOrder extends FocusOrder
class NumericFocusOrder$Mate extends NumericFocusOrder with Mate {
  /// NumericFocusOrder NumericFocusOrder(double order)
  NumericFocusOrder$Mate(

      /// requiredParameters: double order
      double order)
      : super(order) {
    mateBuilder = (p) => NumericFocusOrder$Mate(p.get('order').value);
    mateDeclare('order', order);
  }
}

/// class LexicalFocusOrder extends FocusOrder
class LexicalFocusOrder$Mate extends LexicalFocusOrder with Mate {
  /// LexicalFocusOrder LexicalFocusOrder(String order)
  LexicalFocusOrder$Mate(

      /// requiredParameters: String order
      String order)
      : super(order) {
    mateBuilder = (p) => LexicalFocusOrder$Mate(p.get('order').value);
    mateDeclare('order', order);
  }
}

/// class OrderedTraversalPolicy extends FocusTraversalPolicy with DirectionalFocusTraversalPolicyMixin
class OrderedTraversalPolicy$Mate extends OrderedTraversalPolicy with Mate {
  /// OrderedTraversalPolicy OrderedTraversalPolicy({FocusTraversalPolicy? secondary})
  OrderedTraversalPolicy$Mate(
      {
      /// optionalParameters: {FocusTraversalPolicy? secondary} , defaultValue:none
      FocusTraversalPolicy? secondary})
      : super(secondary: secondary) {
    mateBuilder = (p) => OrderedTraversalPolicy$Mate(secondary: p.get('secondary').build());
    mateDeclare('secondary', secondary);
  }
}

/// class FocusTraversalOrder extends InheritedWidget
class FocusTraversalOrder$Mate extends FocusTraversalOrder with Mate {
  /// FocusTraversalOrder FocusTraversalOrder({Key? key, required FocusOrder order, required Widget child})
  FocusTraversalOrder$Mate({
    /// optionalParameters: {Key? key} , defaultValue:none
    Key? key,

    /// optionalParameters: {required FocusOrder order} , defaultValue:none
    required FocusOrder order,

    /// optionalParameters: {required Widget child} , defaultValue:none
    required Widget child,
  }) : super(
          key: key,
          order: order,
          child: child,
        ) {
    mateBuilder = (p) => FocusTraversalOrder$Mate(
          key: p.get('key').build(),
          order: p.get('order').build(),
          child: p.get('child').build(),
        );
    mateDeclare('key', key);
    mateDeclare('order', order);
    mateDeclare('child', child);
  }
}

/// class FocusTraversalGroup extends StatefulWidget
class FocusTraversalGroup$Mate extends FocusTraversalGroup with Mate {
  /// FocusTraversalGroup FocusTraversalGroup({Key? key, FocusTraversalPolicy? policy, bool descendantsAreFocusable = true, bool descendantsAreTraversable = true, required Widget child})
  FocusTraversalGroup$Mate({
    /// optionalParameters: {Key? key} , defaultValue:none
    Key? key,

    /// optionalParameters: {FocusTraversalPolicy? policy} , defaultValue:none
    FocusTraversalPolicy? policy,

    /// optionalParameters: {bool descendantsAreFocusable = true} , defaultValue:Literal
    bool descendantsAreFocusable = true,

    /// optionalParameters: {bool descendantsAreTraversable = true} , defaultValue:Literal
    bool descendantsAreTraversable = true,

    /// optionalParameters: {required Widget child} , defaultValue:none
    required Widget child,
  }) : super(
          key: key,
          policy: policy,
          descendantsAreFocusable: descendantsAreFocusable,
          descendantsAreTraversable: descendantsAreTraversable,
          child: child,
        ) {
    mateBuilder = (p) => FocusTraversalGroup$Mate(
          key: p.get('key').build(),
          policy: p.get('policy').build(),
          descendantsAreFocusable: p.get('descendantsAreFocusable').build(),
          descendantsAreTraversable: p.get('descendantsAreTraversable').build(),
          child: p.get('child').build(),
        );
    mateDeclare('key', key);
    mateDeclare('policy', policy);
    mateDeclare('descendantsAreFocusable', descendantsAreFocusable);
    mateDeclare('descendantsAreTraversable', descendantsAreTraversable);
    mateDeclare('child', child);
  }
}

/// class RequestFocusIntent extends Intent
class RequestFocusIntent$Mate extends RequestFocusIntent with Mate {
  /// RequestFocusIntent RequestFocusIntent(FocusNode focusNode)
  RequestFocusIntent$Mate(

      /// requiredParameters: FocusNode focusNode
      FocusNode focusNode)
      : super(focusNode) {
    mateBuilder = (p) => RequestFocusIntent$Mate(p.get('focusNode').value);
    mateDeclare('focusNode', focusNode);
  }
}

/// class DirectionalFocusIntent extends Intent
class DirectionalFocusIntent$Mate extends DirectionalFocusIntent with Mate {
  /// DirectionalFocusIntent DirectionalFocusIntent(TraversalDirection direction, {bool ignoreTextFields = true})
  DirectionalFocusIntent$Mate(
    /// requiredParameters: TraversalDirection direction
    TraversalDirection direction, {
    /// optionalParameters: {bool ignoreTextFields = true} , defaultValue:Literal
    bool ignoreTextFields = true,
  }) : super(
          direction,
          ignoreTextFields: ignoreTextFields,
        ) {
    mateBuilder = (p) => DirectionalFocusIntent$Mate(
          p.get('direction').value,
          ignoreTextFields: p.get('ignoreTextFields').build(),
        );
    mateDeclare('direction', direction);
    mateDeclare('ignoreTextFields', ignoreTextFields);
  }
}

/// class ExcludeFocusTraversal extends StatelessWidget
class ExcludeFocusTraversal$Mate extends ExcludeFocusTraversal with Mate {
  /// ExcludeFocusTraversal ExcludeFocusTraversal({Key? key, bool excluding = true, required Widget child})
  ExcludeFocusTraversal$Mate({
    /// optionalParameters: {Key? key} , defaultValue:none
    Key? key,

    /// optionalParameters: {bool excluding = true} , defaultValue:Literal
    bool excluding = true,

    /// optionalParameters: {required Widget child} , defaultValue:none
    required Widget child,
  }) : super(
          key: key,
          excluding: excluding,
          child: child,
        ) {
    mateBuilder = (p) => ExcludeFocusTraversal$Mate(
          key: p.get('key').build(),
          excluding: p.get('excluding').build(),
          child: p.get('child').build(),
        );
    mateDeclare('key', key);
    mateDeclare('excluding', excluding);
    mateDeclare('child', child);
  }
}
