// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/widgets/notification_listener.dart';
import 'package:note/mate.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';

/// class NotificationListener<T extends Notification> extends ProxyWidget
class NotificationListener$Mate<T extends Notification>
    extends NotificationListener<T> with Mate {
  /// NotificationListener<T> NotificationListener({Key? key, required Widget child, bool Function(T)? onNotification})
  NotificationListener$Mate({
    /// optionalParameters: {Key? key} , default:none
    Key? key,

    /// optionalParameters: {required Widget child} , default:none
    required Widget child,

    /// optionalParameters: {bool Function(T)? onNotification} , default:none
    NotificationListenerCallback<T>? onNotification,
  }) : super(
          key: key,
          child: child,
          onNotification: onNotification,
        ) {
    mateBuilderName = 'NotificationListener';
    matePackageUrl = 'package:flutter/widgets.dart';
    mateBuilder = (p) => NotificationListener$Mate<T>(
          key: p.get('key').build(),
          child: p.get('child').build(),
          onNotification: p.get('onNotification').build(),
        );
    mateUse(
      'key',
      key,
      isNamed: true,
    );
    mateUse(
      'child',
      child,
      isNamed: true,
    );
    mateUse(
      'onNotification',
      onNotification,
      isNamed: true,
    );
  }
}
