// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/widgets/router.dart';
import 'package:note/mate.dart';
import 'dart:core';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/foundation/basic_types.dart';
import 'dart:async';

/// class RouteInformation
class RouteInformation$Mate extends RouteInformation with Mate {
  /// RouteInformation RouteInformation({String? location, Object? state})
  RouteInformation$Mate({
    /// optionalParameters: {String? location} , hasDefaultValue:false, defaultValueCode:null
    String? location,

    /// optionalParameters: {Object? state} , hasDefaultValue:false, defaultValueCode:null
    Object? state,
  }) : super(
          location: location,
          state: state,
        ) {
    mateBuilder = (p) => RouteInformation$Mate(
          location: p.get('location').build(),
          state: p.get('state').build(),
        );
    matePut('location', location);
    matePut('state', state);
  }
}

/// class RouterConfig<T>
class RouterConfig$Mate<T> extends RouterConfig<T> with Mate {
  /// RouterConfig<T> RouterConfig({RouteInformationProvider? routeInformationProvider, RouteInformationParser<T>? routeInformationParser, required RouterDelegate<T> routerDelegate, BackButtonDispatcher? backButtonDispatcher})
  RouterConfig$Mate({
    /// optionalParameters: {RouteInformationProvider? routeInformationProvider} , hasDefaultValue:false, defaultValueCode:null
    RouteInformationProvider? routeInformationProvider,

    /// optionalParameters: {RouteInformationParser<T>? routeInformationParser} , hasDefaultValue:false, defaultValueCode:null
    RouteInformationParser<T>? routeInformationParser,

    /// optionalParameters: {required RouterDelegate<T> routerDelegate} , hasDefaultValue:false, defaultValueCode:null
    required RouterDelegate<T> routerDelegate,

    /// optionalParameters: {BackButtonDispatcher? backButtonDispatcher} , hasDefaultValue:false, defaultValueCode:null
    BackButtonDispatcher? backButtonDispatcher,
  }) : super(
          routeInformationProvider: routeInformationProvider,
          routeInformationParser: routeInformationParser,
          routerDelegate: routerDelegate,
          backButtonDispatcher: backButtonDispatcher,
        ) {
    mateBuilder = (p) => RouterConfig$Mate<T>(
          routeInformationProvider: p.get('routeInformationProvider').build(),
          routeInformationParser: p.get('routeInformationParser').build(),
          routerDelegate: p.get('routerDelegate').build(),
          backButtonDispatcher: p.get('backButtonDispatcher').build(),
        );
    matePut('routeInformationProvider', routeInformationProvider);
    matePut('routeInformationParser', routeInformationParser);
    matePut('routerDelegate', routerDelegate);
    matePut('backButtonDispatcher', backButtonDispatcher);
  }
}

/// class Router<T> extends StatefulWidget
class Router$Mate<T> extends Router<T> with Mate {
  /// Router<T> Router({Key? key, RouteInformationProvider? routeInformationProvider, RouteInformationParser<T>? routeInformationParser, required RouterDelegate<T> routerDelegate, BackButtonDispatcher? backButtonDispatcher, String? restorationScopeId})
  Router$Mate({
    /// optionalParameters: {Key? key} , hasDefaultValue:false, defaultValueCode:null
    Key? key,

    /// optionalParameters: {RouteInformationProvider? routeInformationProvider} , hasDefaultValue:false, defaultValueCode:null
    RouteInformationProvider? routeInformationProvider,

    /// optionalParameters: {RouteInformationParser<T>? routeInformationParser} , hasDefaultValue:false, defaultValueCode:null
    RouteInformationParser<T>? routeInformationParser,

    /// optionalParameters: {required RouterDelegate<T> routerDelegate} , hasDefaultValue:false, defaultValueCode:null
    required RouterDelegate<T> routerDelegate,

    /// optionalParameters: {BackButtonDispatcher? backButtonDispatcher} , hasDefaultValue:false, defaultValueCode:null
    BackButtonDispatcher? backButtonDispatcher,

    /// optionalParameters: {String? restorationScopeId} , hasDefaultValue:false, defaultValueCode:null
    String? restorationScopeId,
  }) : super(
          key: key,
          routeInformationProvider: routeInformationProvider,
          routeInformationParser: routeInformationParser,
          routerDelegate: routerDelegate,
          backButtonDispatcher: backButtonDispatcher,
          restorationScopeId: restorationScopeId,
        ) {
    mateBuilder = (p) => Router$Mate<T>(
          key: p.get('key').build(),
          routeInformationProvider: p.get('routeInformationProvider').build(),
          routeInformationParser: p.get('routeInformationParser').build(),
          routerDelegate: p.get('routerDelegate').build(),
          backButtonDispatcher: p.get('backButtonDispatcher').build(),
          restorationScopeId: p.get('restorationScopeId').build(),
        );
    matePut('key', key);
    matePut('routeInformationProvider', routeInformationProvider);
    matePut('routeInformationParser', routeInformationParser);
    matePut('routerDelegate', routerDelegate);
    matePut('backButtonDispatcher', backButtonDispatcher);
    matePut('restorationScopeId', restorationScopeId);
  }
}

/// class ChildBackButtonDispatcher extends BackButtonDispatcher
class ChildBackButtonDispatcher$Mate extends ChildBackButtonDispatcher with Mate {
  /// ChildBackButtonDispatcher ChildBackButtonDispatcher(BackButtonDispatcher parent)
  ChildBackButtonDispatcher$Mate(

      /// requiredParameters: BackButtonDispatcher parent
      BackButtonDispatcher parent)
      : super(parent) {
    mateBuilder = (p) => ChildBackButtonDispatcher$Mate(p.get('parent').value);
    matePut('parent', parent);
  }
}

/// class BackButtonListener extends StatefulWidget
class BackButtonListener$Mate extends BackButtonListener with Mate {
  /// BackButtonListener BackButtonListener({Key? key, required Widget child, required Future<bool> Function() onBackButtonPressed})
  BackButtonListener$Mate({
    /// optionalParameters: {Key? key} , hasDefaultValue:false, defaultValueCode:null
    Key? key,

    /// optionalParameters: {required Widget child} , hasDefaultValue:false, defaultValueCode:null
    required Widget child,

    /// optionalParameters: {required Future<bool> Function() onBackButtonPressed} , hasDefaultValue:false, defaultValueCode:null
    required ValueGetter<Future<bool>> onBackButtonPressed,
  }) : super(
          key: key,
          child: child,
          onBackButtonPressed: onBackButtonPressed,
        ) {
    mateBuilder = (p) => BackButtonListener$Mate(
          key: p.get('key').build(),
          child: p.get('child').build(),
          onBackButtonPressed: p.get('onBackButtonPressed').build(),
        );
    matePut('key', key);
    matePut('child', child);
    matePut('onBackButtonPressed', onBackButtonPressed);
  }
}

/// class PlatformRouteInformationProvider extends RouteInformationProvider with WidgetsBindingObserver, ChangeNotifier
class PlatformRouteInformationProvider$Mate extends PlatformRouteInformationProvider with Mate {
  /// PlatformRouteInformationProvider PlatformRouteInformationProvider({required RouteInformation initialRouteInformation})
  PlatformRouteInformationProvider$Mate(
      {
      /// optionalParameters: {required RouteInformation initialRouteInformation} , hasDefaultValue:false, defaultValueCode:null
      required RouteInformation initialRouteInformation})
      : super(initialRouteInformation: initialRouteInformation) {
    mateBuilder =
        (p) => PlatformRouteInformationProvider$Mate(initialRouteInformation: p.get('initialRouteInformation').build());
    matePut('initialRouteInformation', initialRouteInformation);
  }
}
