// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/widgets/view.dart';
import 'package:note/mate.dart';
import 'dart:ui';
import 'package:flutter/src/widgets/framework.dart';

/// class View extends StatelessWidget
class View$Mate extends View with Mate {
  /// View View({required FlutterView view, required Widget child})
  View$Mate({
    /// optionalParameters: {required FlutterView view} , defaultValue:none
    required FlutterView view,

    /// optionalParameters: {required Widget child} , defaultValue:none
    required Widget child,
  }) : super(
          view: view,
          child: child,
        ) {
    mateCreateName = 'View';
    matePackageUrl = 'package:flutter/widgets.dart';
    mateBuilder = (p) => View$Mate(
          view: p.get('view').build(),
          child: p.get('child').build(),
        );
    mateUse('view', view);
    mateUse('child', child);
  }
}
