// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/services/raw_keyboard_web.dart';
import 'dart:core';
import 'package:note/mate.dart';

/// class RawKeyEventDataWeb extends RawKeyEventData
class RawKeyEventDataWeb$Mate extends RawKeyEventDataWeb with Mate<RawKeyEventDataWeb$Mate> {
  /// RawKeyEventDataWeb RawKeyEventDataWeb({required String code, required String key, int location = 0, int metaState = modifierNone, int keyCode = 0})
  RawKeyEventDataWeb$Mate({
    /// optionalParameters: {required String code} , hasDefaultValue:false, defaultValueCode:null
    required String code,

    /// optionalParameters: {required String key} , hasDefaultValue:false, defaultValueCode:null
    required String key,

    /// optionalParameters: {int location = 0} , hasDefaultValue:true, defaultValueCode:0
    required int location,

    /// optionalParameters: {int metaState = modifierNone} , hasDefaultValue:true, defaultValueCode:modifierNone
    required int metaState,

    /// optionalParameters: {int keyCode = 0} , hasDefaultValue:true, defaultValueCode:0
    required int keyCode,
  }) : super(
          code: code,
          key: key,
          location: location,
          metaState: metaState,
          keyCode: keyCode,
        ) {
    mateParams = ObjectParam(
      init: this,
      builder: (p) => RawKeyEventDataWeb$Mate(
        code: p.get('code').build(),
        key: p.get('key').build(),
        location: p.get('location').build(),
        metaState: p.get('metaState').build(),
        keyCode: p.get('keyCode').build(),
      ),
    );
    mateParams.put('code', code);
    mateParams.put('key', key);
    mateParams.put('location', location);
    mateParams.put('metaState', metaState);
    mateParams.put('keyCode', keyCode);
  }
}
