// /// Generated by gen_maters.dart, please don't edit!

import 'package:flutter/src/services/raw_keyboard.dart';
import 'package:note/mate.dart';
import 'dart:core';

/// class RawKeyDownEvent extends RawKeyEvent
class RawKeyDownEvent$Mate extends RawKeyDownEvent with Mate {
  /// RawKeyDownEvent RawKeyDownEvent({required RawKeyEventData data, String? character, bool repeat = false})
  RawKeyDownEvent$Mate({
    /// optionalParameters: {required RawKeyEventData data} , hasDefaultValue:false, defaultValueCode:null
    required RawKeyEventData data,

    /// optionalParameters: {String? character} , hasDefaultValue:false, defaultValueCode:null
    String? character,

    /// optionalParameters: {bool repeat = false} , hasDefaultValue:true, defaultValueCode:false
    required bool repeat,
  }) : super(
          data: data,
          character: character,
          repeat: repeat,
        ) {
    mateBuilder = (p) => RawKeyDownEvent$Mate(
          data: p.get('data').build(),
          character: p.get('character').build(),
          repeat: p.get('repeat').build(),
        );
    matePut('data', data);
    matePut('character', character);
    matePut('repeat', repeat);
  }
}

/// class RawKeyUpEvent extends RawKeyEvent
class RawKeyUpEvent$Mate extends RawKeyUpEvent with Mate {
  /// RawKeyUpEvent RawKeyUpEvent({required RawKeyEventData data, String? character})
  RawKeyUpEvent$Mate({
    /// optionalParameters: {required RawKeyEventData data} , hasDefaultValue:false, defaultValueCode:null
    required RawKeyEventData data,

    /// optionalParameters: {String? character} , hasDefaultValue:false, defaultValueCode:null
    String? character,
  }) : super(
          data: data,
          character: character,
        ) {
    mateBuilder = (p) => RawKeyUpEvent$Mate(
          data: p.get('data').build(),
          character: p.get('character').build(),
        );
    matePut('data', data);
    matePut('character', character);
  }
}
