// /// Generated by mat_flutter, please don't edit! Created time: 2023-03-09 00:15:59.383869

library;

import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/painting/text_style.dart';
import 'package:flutter/src/painting/edge_insets.dart';
import 'dart:core';
import 'package:flutter/src/painting/borders.dart';
import 'dart:ui';
import 'package:flutter/src/widgets/focus_manager.dart';
import 'package:flutter/src/material/theme_data.dart';
import 'package:flutter/src/widgets/icon_theme_data.dart';

/// class ActionChip extends StatelessWidget implements ChipAttributes, TappableChipAttributes, DisabledChipAttributes
class ActionChipMate {
  /// ActionChip ActionChip({Key? key, Widget? avatar, required Widget label, TextStyle? labelStyle, EdgeInsetsGeometry? labelPadding, void Function()? onPressed, double? pressElevation, String? tooltip, BorderSide? side, OutlinedBorder? shape, Clip clipBehavior = Clip.none, FocusNode? focusNode, bool autofocus = false, Color? backgroundColor, Color? disabledColor, EdgeInsetsGeometry? padding, VisualDensity? visualDensity, MaterialTapTargetSize? materialTapTargetSize, double? elevation, Color? shadowColor, Color? surfaceTintColor, IconThemeData? iconTheme})
  ActionChipMate({
// param: {Key? key}
    Key? key,
// param: {Widget? avatar}
    Widget? avatar,
// param: {required Widget label}
    required Widget label,
// param: {TextStyle? labelStyle}
    TextStyle? labelStyle,
// param: {EdgeInsetsGeometry? labelPadding}
    EdgeInsetsGeometry? labelPadding,
// param: {void Function()? onPressed}
    void Function()? onPressed,
// param: {double? pressElevation}
    double? pressElevation,
// param: {String? tooltip}
    String? tooltip,
// param: {BorderSide? side}
    BorderSide? side,
// param: {OutlinedBorder? shape}
    OutlinedBorder? shape,
// param: {Clip clipBehavior = Clip.none}
    required Clip clipBehavior,
// param: {FocusNode? focusNode}
    FocusNode? focusNode,
// param: {bool autofocus = false}
    required bool autofocus,
// param: {Color? backgroundColor}
    Color? backgroundColor,
// param: {Color? disabledColor}
    Color? disabledColor,
// param: {EdgeInsetsGeometry? padding}
    EdgeInsetsGeometry? padding,
// param: {VisualDensity? visualDensity}
    VisualDensity? visualDensity,
// param: {MaterialTapTargetSize? materialTapTargetSize}
    MaterialTapTargetSize? materialTapTargetSize,
// param: {double? elevation}
    double? elevation,
// param: {Color? shadowColor}
    Color? shadowColor,
// param: {Color? surfaceTintColor}
    Color? surfaceTintColor,
// param: {IconThemeData? iconTheme}
    IconThemeData? iconTheme,
  }) {}
}
